### ISSUE TITLE
Optimizing evaluation of userset relationships during Check evaluation

### ISSUE THREAD

**Issue by jon-whit** [openfga/openfga#1012]
If there exist relationships with usersets when evaluating a Check query, then we have an opportunity to optimize these evaluations by iteratively batching and concurrently processing the batches instead of accumulating synchronously and then evaluating concurrently. Doing this will effectively make sub-graph evaluations of these userset lookups more responsive.

Here is the code that can be improved:
https://github.com/openfga/openfga/blob/main/internal/graph/check.go#L552-L607

Notice how we consume the whole iterator and then concurrently evaluate the CheckFuncHandlers afterwards..

My recommendation would be to change the implementation such that we iteratively consume the iterator (in batches up to some size) and then concurrently evaluate those batches. The idea is that this approach will make sub-graph evaluation more responsive since we will start processing the various branches of the graph more responsively as compared to how it works today. For example, consider the following model and relationship tuples:

```
type user

type group
  relations
    define member: [user]

type document
  relations
    define viewer: [group#member]
```

```
- document:1#viewer@group:1#member
- document:1#viewer@group:2#member
- ...
- document:1#viewer@group:N#member
- group:1#member@user:jon
```

When evaluating a Check query of the form `Check(document:1#viewer@user:jon)`, and if `N` is large, then [consuming the iterator](https://github.com/openfga/openfga/blob/main/internal/graph/check.go#L554) will take a long time, and that is time spent that could otherwise be spent processing the first batches of relationships that will quickly find a resolution path. If we were to consume the iterator in batches of 2 then we would process the following relationships very quickly, even before the whole N items from the iterator have been consumed:
```
- group:1#member@user:jon
- group:2#member@user:jon
```
and from these initial `group#member` usersets in the first batch of 2, we will find that `user:jon` is related to `group:1#member`, and thus we have found a resolution path with more responsiveness as compared to the alternative (consume all N values from the iterator and then process).

Another added benefit of this approach is that it reduces the potential for a sudden fanout of evaluation that would otherwise take place, and that can potentially reduce the impact to the database and resource footprint of the query (less required goroutines etc..). Using the example above, if we consume the iterator in batches of 2 and then dispatch the subproblems as we batch them, then we can potentially avoid dispatching thousands or more of subproblems in the first place because we will find a resolution path before we even consume the other values from the iterator.

**Comment by miparnisari** [comment]
Addressed in https://github.com/openfga/openfga/issues/1012
