### ISSUE TITLE
Check links in the README as part of the CI/CD

### ISSUE THREAD

**Issue by rhamzeh** [openfga/openfga#1014]
**Summary**

As a followup to #1013, we can avoid this situation by adding an action to check the links in the README.md using something like https://github.com/gaurav-nelson/github-action-markdown-link-check in our workflow.

It would not block merges, but allow us to catch stale links faster without waiting for users to stumble on them

**Comment by gabrielbussolo** [comment]
seems like it was closed by https://github.com/openfga/openfga/pull/1016
