### ISSUE TITLE
HELP - Open FGA Wildcard Relationship From Object to User

### ISSUE THREAD

**Issue by JRudransh** [openfga/openfga#1026]
I am trying to define user and admin schema in OpenFga

```
model
  schema 1.1
type user
  relations
    define admin: [admin#member]
type admin
  relations
    define member: [user]
```

I have added relationship where I have a user to admin relationship
```
User     admin:identity_admin
Relation admin
Object   user:rahul
```

I want to add a relationship wher all future user's admin should be `admin:identity_admin`. Something like

```
User     admin:identity_admin
Relation admin
Object   user:*
```

But seems like this is not supported by OpenFGA or I may be missing something. Any help will be appriciated

I have posted the same issue in StackOverflow. Link: https://stackoverflow.com/q/77185805/12199927

**Comment by velmohan** [comment]
@JRudransh  you are correct.  The type bound public access cannot be used in "Object" field.

I am not sure what your use case is but you can do this if you can reverse the relationship
`
`

**Comment by JRudransh** [comment]
Thanks @velmohan for your response. Our current flow does not support the reverse implementation. My use case is very simple, a particular type of admin should be admin of all users. That is my requirement

**Comment by jon-whit** [comment]
@JRudransh I may not understand the requirements completely, so forgive me if this overlooks the use case. If you can provide some sample Check queries that you would be making that may help. But would the following work?

```
model
  schema 1.1

type user
    relations
        define organization: [organization]
        define managed_by: manage_users from organization

type organization
    relations
        define admin: [user]
        define manage_users: [organization#admin]
```

```
- organization:acme#manage_users@organization:acme#admin
- organization:acme#admin@user:bob
- user:x#organization@organization:acme
- 
```

```
Check(user:x#managed_by@user:bob) --> {allowed: true}
Check(user:x#managed_by@user:jim) --> {allowed: false}
```

But now `user:jim` joins the `organization:acme#admin` group and will be able to manage `user:x`.
```
- organization:acme#admin@user:jim

Check(user:x#managed_by@user:jim) --> {allowed: true}
```

The idea is that each user is part of the owning organization and a user can be managed by anyone who can manage users of the organization. Users that are part of the admin group of the organization can manage users of the organization, and therefore anytime a user is made an admin they can manage the users of the organization.

If only I had a dollar for every time I used the word "users" in the paragraph above.. 😄 !

**Comment by JRudransh** [comment]
Thanks @jon-whit for your response. We have already gone with a model. And that model is similar to your example model.

Organization will be the top level entity. When a user joins the organization, the organization admin will be able to manage that user.

**Comment by jon-whit** [comment]
@JRudransh awesome! Glad we came to similar solutions. I think that should work well for your use case. Let us know otherwise. For now I'll mark this as resolved. If further questions come up feel free to open another follow up conversation and link back to this.
