### ISSUE TITLE
Use options builder pattern for command constructors

### ISSUE THREAD

**Issue by jpadilla** [openfga/openfga#1039]
Can we follow up and replace this kind of stuff (here and elsewhere) with the options builder pattern? The default should be used if the option isn't explicitly set. You shouldn't have to explicitly set it if it's a default 😄

e.g.

```
NewWriteAuthorizationModelCommand(datastore, WithLogger(logger), WithAuthorizationModelSizeInBytes(2048)) // if non-defaults are desired, otherwise

NewWriteAuthorizationModelCommand(datastore)
```

_Originally posted by @jon-whit in https://github.com/openfga/openfga/pull/1036#discussion_r1344851323_

**Comment by ilaleksin** [comment]
Hey, I would be happy to contribute to this enhancement.

May I work on it?

**Comment by miparnisari** [comment]
@ilaleksin sure!
