### ISSUE TITLE
When OPENFGA_LIST_OBJECTS_MAX_RESULTS=0, 0 results are returned

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1044]
Hi @miparnisari  and @jon-whit.

We've been experimenting with OpenFGA at Cochlear and we'd like to appreciate the amazing work you've been doing. It's awesome to see this how this project's evolving.

On a more codebase related question: How are you ensuring you return all data when `OPENFGA_LIST_OBJECTS_MAX_RESULTS` is set to `0`?

I couldn't find any test case that validates that flow.

Also, that setting doesn't seem to work for me. I'm happy to help and contribute with a fix if that's the case.

Thank you!

_Originally posted by @jcbertolucci in https://github.com/openfga/openfga/issues/757#issuecomment-1747893509_

**Comment by miparnisari** [comment]
Seems like it broke in this commit https://github.com/openfga/openfga/commit/5c7c5c88dd07c85666275621503f867428a59693 because the previous commit respects the 0 value

**Comment by miparnisari** [comment]
@jcbertolucci this was released as part of 1.3.5. Thanks for the report!

**Comment by jcbertolucci** [comment]
@miparnisari all good! You guys are the rockstars here.

Thank you for the quick turnaround ♥️
