### ISSUE TITLE
Add support for multiple oidc issuers

### ISSUE THREAD

**Issue by tnarg** [openfga/openfga#1090]
It is currently only possible to specify a single oidc issuer. In some environments each microservice has its own oidc issuer. To allow multiple services to authenticate with an openfga instance in such an environment, openfga needs to be modified to accept multiple issuers.

**Comment by yann-disanto** [comment]
We have another use case for multiple issuers. Our OpenFGA service is deployed in a kubernetes cluster and some services use the issuer kube alias (for internal calls) but we also may have tokens delivered by the authority with the public dns.

**Comment by le-yams** [comment]
Here is a draft PR allowing to specify issuer aliases: #1354 . 
The aliases are used as acceptable values for the token issuer validation (`iss` claim). Note that it still rely on the main issuer jwks for the token validation so it might not fully address the initial use-case.

**Comment by miparnisari** [comment]
Release 1.5.1 (https://github.com/openfga/openfga/releases/tag/v1.5.1) includes support for issuer aliases.
