### ISSUE TITLE
Question about conditional relationship tuples

### ISSUE THREAD

**Issue by geoffroybraun** [openfga/openfga#1156]
Hi all,

I saw your [blog post about conditional relationship tuples](https://openfga.dev/blog/conditional-tuples-announcement), pretty excited about it as this is a functionality we were really looking for! I just have a question about the way I can use it in a use case I already described in another ticket (if I can use it...).

Let say I have the following authorization model, where users own houses and houses belong to quarters, helping me getting residents of a quarter.

```yaml
model
    schema 1.1
type user
type house
    relations
        define owner: [user]
        define resident: [user] or owner
type quarter
    relations
        define belong_to: [house]
        define resident: resident from belong_to
```

Now, the use case would be something like : 

_I want to declare a relation `supervisor` between `user` and `quarter` as far as the `user` has the relation `resident` with the quarter._

With the help of your conditional relationship tuples, I thought about defining a condition to check the `user` actually has the `resident` relation with the `quarter` before being added as `supervisor`. This would lead to the following authorization model.

```yaml
model
    schema 1.1
type user
type house
    relations
        define owner: [user]
        define resident: [user] or owner
type quarter
    relations
        define belong_to: [house]
        define resident: resident from belong_to
        define supervisor: [user with quarter_resident]

condition quarter_resident(user_id: string, quarter_id: string) {
  // Do stuff here
}
```

As you can see, I absolutly have no idea if conditional relationship tuples can help me with my use case, and event worse, I absolutly no idea how to implement it... Can you please let me know if thise would work, and if so, how can it work?

Cheers!

**Comment by aaguiarz** [comment]
Hi @geoffroybraun 

Do you want to prevent the `supervisor` relationship to be added if the user is not in the quarter? If so, you can't enforce that constraint in the model, you'll need to call check(user:x, resident, quarter:y) before adding the relationship.

If you want to make sure that if the relationship was added by mistake, calling check(user:x, supervisor, quarter:y) returns `allowed : false`, you can define the `supervisor` relationship as

`define supervisor: [user] and resident`

Does this make sense, or did I misunderstand the problem you want to solve?

**Comment by geoffroybraun** [comment]
Hi @aaguiarz,

thank you very much for the more than quick reply! 

The idea is to block the ability to add a `user` as `supervisor` if he/she has not a `resident` relation with the targeted `quarter`. I understand I should check the `user` is `resident` of a `quarter` before adding him/her as `supervisor` on our side, I was just wondering if this was possible within the authorization model to avoid checking multiple relations.

If not, fair enough, we will do it from code.

Thanks!

**Comment by geoffroybraun** [comment]
Alright, that seems fine for me. Just for the record, the `define supervisor: [user] and resident` line is really helpful and unlocks another use case we have, so even tho I can't use conditional relationship tuples, you still helped for another topic without knowing it, so thank you very much for that.

Wishing you a nice WE in advance!

**Comment by aaguiarz** [comment]
Glad it helped, have a nice weekend too! :)
