### ISSUE TITLE
[Help needed] Add a member of an organization to one of the organization's project 

### ISSUE THREAD

**Issue by ruppo-912116** [openfga/openfga#1165]
## Description

I want to add a member who is a member of an organization to one of the project inside the organization but keep on getting error this error 
`Invalid tuple 'project:metap1#member@user:loki'. Reason: type 'user' is not an allowed type restriction for 'project#member'`. 

Note: I want to check if the user is a member of the organization 

I was successful in adding these relationship tuples:
1. User loki is a member of the organization meta.
```
USER user:loki
RELATION member
OBJECT organization:meta
```

2. the owner of the project metap1 is the organization meta  
```
USER organization:meta
RELATION owner
OBJECT project:metap1
```
but when trying to add the user loki to project metap1, I am having an issue. 
```
USER user:loki
RELATION member
OBJECT project:metap1
```

My authorization model is below:
```
model
  schema 1.1

type user

type organization
  relations
    define owner: [user, organization#member]
    define member: [user] or owner
    
type project
  relations
    define parent: [organization]
    define owner: [organization]
    define manager: [organization#member]
    define can_add_member: [organization#owner] or manager
    define member: [organization#member]

```

I have recently started learning openfga and i am currently trying this on openfga playground for learning. Can anyone help?

**Comment by aaguiarz** [comment]
Hi @ruppo-912116 

When you define:

    `define manager: [organization#member]`

you are telling OpenFGA that you can assign 'all members of an organization' as a manager, and you'd write a tuple like

USER: organization:meta#member RELATION: member OBJECT: project: metap1

If you want to assign specific users as members/managers you'd write a model like:

```
model
  schema 1.1

type user

type organization
  relations
    define owner: [user]
    define member: [user] or owner
    
type project
  relations
    define parent: [organization]
    define manager: [user]
    define member: member from organization
    define can_add_member:  manager or owner from organization
```

Let me know if it helps

**Comment by ruppo-912116** [comment]
Hi @aaguiarz, 
Using `member from organization` gives me the error `organization is not a valid relation for project` in my playground that I ran locally using this docker-compose https://github.com/openfga/openfga/blob/main/docker-compose.yaml. so, I used `member from parent` inside, but it still gives me the same error `Invalid tuple 'project:metap1#member@user:loki'. Reason: type 'user' is not an allowed type restriction for project#member`. my tuple was this:
```
USER user:loki
RELATION member
OBJECT project:metap1
```

**Comment by aaguiarz** [comment]
I'm sorry, the model is:

model
  schema 1.1
```
type user

type organization
  relations
    define owner: [user]
    define member: [user] or owner
    
type project
  relations
    define parent: [organization]
    define manager: [user]
    define member: member from organization
    define can_add_member:  manager or owner from parent
```

You can't write this tuple

```
USER user:loki
RELATION member
OBJECT project:metap1
```

Because you can't assign the 'member' relation in the `project` type. If you want to achieve that, you'll need to change the member definition to:

` define member: [user] or member from organization`

With the first two tuples you defined, you can check if user:loki is a member for project:metap1, and it should return true, given user:loki is a member of the organization:meta which is the parent from project:metap1.

**Comment by ruppo-912116** [comment]
@aaguiarz,
This works but it also add users who are not even in the organization. i tried a different user flash who is associated with the other organization but the user was still added. also, the graph does not show the organization at all.

![image](https://github.com/openfga/openfga/assets/84317977/c3cb2a53-c99e-4186-bf07-dad6093f14e8)

**Comment by aaguiarz** [comment]
Yes, the model allows adding any user. If you want to enforce that the `member` relationship will only exist if the users are member of the organization, then you'd write

` define member: [user] and member from parent`

However, given your application is the one adding tuples, you could verify yourself that the user is part of the organization before adding it.

**Comment by ruppo-912116** [comment]
@aaguiarz 
I had the same idea using `and` operator but it also does not seem to work, surprisingly. 
I think I need to add the extra bit of logic on my application. 
thank you for helping.
