### ISSUE TITLE
Assertions with context

### ISSUE THREAD

**Issue by ofeksher** [openfga/openfga#1181]
Is it possible to write Assertions with context?

**Comment by aaguiarz** [comment]
Hi @ofeksher not yet, but it's supported in the [CLI](https://github.com/openfga/cli#run-tests-on-an-authorization-model), you can see how we use them in our examples [here](https://github.com/openfga/sample-stores/blob/main/stores/advanced-entitlements/store.fga.yaml) 

Let me know if that helps
