### ISSUE TITLE
Support for reverse queries for 

### ISSUE THREAD

**Issue by fsedano** [openfga/openfga#1215]
**Summary**

Is there a way to do reverse lookup of users and subjects?

I'm evaluating OpenFGA against SpiceDB. One very nice feature in SpiceDB is it supports both LookupResources and LookupSubjects. I only saw 'list-objects' API in OpenFGA (that would be equivalent of 'LookupResources) but I could not find the opposite.

I.e. I want both 'which users have READER relation with DOC1' and 'Which docs can USER1 access as READER'

**Comment by rhamzeh** [comment]
Hi @fsedano! Thanks for asking.

Right now we do not have it yet, however it is an upcoming feature in our roadmap as ListUsers

https://github.com/orgs/openfga/projects/1/views/1?pane=issue&itemId=24490812

**Comment by fsedano** [comment]
@aaguiarz We discussed about this on Kubecon today, from what I understood is already shipping? Your response above suggests it's on roadmap.

**Comment by aaguiarz** [comment]
Hi @fsedano , what we shipped is ListObjects, we are currently working on ListUsers, the RFC is here https://github.com/openfga/rfcs/blob/main/20231214-listUsers-api.md
