### ISSUE TITLE
Deleting tuples without known relation.

### ISSUE THREAD

**Issue by Nizio-Dev** [openfga/openfga#1223]
In my use-case I have groups, where an User can be of role member, super_member or owner. If I want to revoke his rights, I need to query every tuple containing his membership-type relation and then map it to a new tuple to be deleted. Could a feature be added in the future, where you can specify wildcard, or just not define relation at all to delete given user's tuples in given object?

**Comment by jon-whit** [comment]
@Nizio-Dev we're looking at improvements we'd like to introduce in a new major API version of OpenFGA. Part of those changes will likely include a Delete with filter endpoint where you can delete any tuples matching an arbitrary filter on any of the fields provided. I believe this would help you meet your ideal goals.

We're aware of our current API short-comings and have some roadmap plans to address them.

**Comment by zgrose** [comment]
+1
An API version of the Tuple Management screen in the Dashboard UI would be very handy and I think would handle the OP and my own use-case (drop all tuples with `user:bob` regardless of object or relation).

**Comment by aaguiarz** [comment]
We'll cover this scenario as part of this roadmap item https://github.com/openfga/roadmap/issues/34

**Comment by rhamzeh** [comment]
Currently, the way to do that would be to call Read, and then follow that with a Write to delete all the returned tuples. Below is an example using the [JS SDK](https://github.com/openfga/js-sdk)
```js
const { tuples } = await fgaClient.read({
  user: "user:81684243-9356-4421-8fbf-a4f8d36aa31b",
  object: "document:roadmap",
});

const { tuples } = await fgaClient.write({
  deletes: tuples, // make sure to chunk by 40 if the tuples are > 40
});
```


Or if this is a one of, and you do not want to use the SDK, you can use the [CLI](https://github.com/openfga/cli/?tab=readme-ov-file#delete-relationship-tuples):
```sh
fga tuple read --user user:81684243-9356-4421-8fbf-a4f8d36aa31b --object document:roadmap --output-format=simple-json --max-pages=0 > tuples.json
fga tuple delete --file tuples.json
```
