### ISSUE TITLE
Unable to create Authorization Model using WriteAuthorizatoinModel (grpc) method

### ISSUE THREAD

**Issue by sasanknvs** [openfga/openfga#1224]
**Summary**

I am running openfga container on my local machine using postgres. Using postman I am trying to write authorization model using grpc endpoints.

- Steps to reproduce
  Model an authorization model and try to create it using WriteAuthorizationModel method. Provided the model I am using in the below sections 
- What did you expect to happen?
  Authorization model creation successful and Id in response
- What actually happened?
  Authorization model failed to create with the an error in the json structure input to the endpoint. I also tried to create same authorization model through a Rest endpoint and I was able to create it. When I try to retrieve it with grpc endpoint I got the response in a different Json structure than the input.

**OpenFGA version or commit**

If you know it, enter here.

**Store data**

Below the authorization model I tried to populate to grpc endpoint. The same worked well and am able to create Authorization model successfully with Rest endpoint. I have checked the SDK model classes, they look different from that of the json I am inputting. But I am following the same syntax and configuration language that is specified in the documentation.

```json
{
  "schema_version": "1.1",
  "type_definitions": [
    {
      "type": "user"
    },
    {
      "type": "document",
      "relations": {
        "reader": {
          "this": {}
        },
        "writer": {
          "this": {}
        },
        "owner": {
          "this": {}
        }
      },
      "metadata": {
        "relations": {
          "reader": {
            "directly_related_user_types": [
              {
                "type": "user"
              }
            ]
          },
          "writer": {
            "directly_related_user_types": [
              {
                "type": "user"
              }
            ]
          },
          "owner": {
            "directly_related_user_types": [
              {
                "type": "user"
              }
            ]
          }
        }
      }
    }
  ]
}
```

**Other data**

- How are you running OpenFGA? Docker 
- What datastore are you using? Postgres
- Are you running OpenFGA with any configuration overrides or with any of the flags mentioned in `./openfga run --help`?
- Do you have any logs or traces that could help us debug the problem? No

**Comment by jon-whit** [comment]
@sasanknvs please fill out the section that reports the OpenFGA version you are running with. Without that it's going to be hard to reliably reproduce.

**Comment by sasanknvs** [comment]
> @sasanknvs please fill out the section that reports the OpenFGA version you are running with. Without that it's going to be hard to reliably reproduce.
> 
> Also, could you share the gRPC request you are making? I see you reported a JSON model. I would expect to see a `grpcurl` or similar request body. We'll need that to reproduce.

I understood the problem. I am using the authorization model in json format from Openfga documentation and using it as a grpc message body. That's why I am seeing the issue. 

Can you let me to know if there is any sdk/client available if I want to communicate with openfga's  grpc endpoint ?

**Comment by jon-whit** [comment]
@sasanknvs our SDKs do not currently support the gRPC endpoint(s). We have gRPC client support in our SDKs in the roadmap. However, the gRPC server of OpenFGA supports the gRPC reflection protocol and various tools like Postman support gRPC and can use the reflection endpoint to generate sample requests.

<img width="1071" alt="Screenshot 2023-12-12 at 3 36 52 PM" src="https://github.com/openfga/openfga/assets/2899204/db9f5bf2-8e59-4ddb-9903-3f42e0fb63fd">

**Comment by miparnisari** [comment]
@sasanknvs I'm going to close this. Feel free to open a new issue if you have more questions 👍
