### ISSUE TITLE
Test data should not have emails and should use openfga/openfga as a refrence repo

### ISSUE THREAD

**Issue by rhamzeh** [openfga/openfga#123]
- Users in tests such as [here](https://github.com/openfga/openfga/blob/main/server/test/write.go) should drop the `@auth0.com` email (generally we should avoid using emails in test data)
- Repositories in tests can be switched to `repository:openfga/openfga`?

**Comment by dblclik** [comment]
@rhamzeh - I can take this chore/issue 👍

**Comment by rhamzeh** [comment]
Thanks for taking this on @dblclik!
