### ISSUE TITLE
Release `v0.1.5` has not been released yet

### ISSUE THREAD

**Issue by vavsab** [openfga/openfga#124]
Hi team. Just found out that docker build in dockerhub is too old. It does not support this section
https://openfga.dev/docs/getting-started/setup-openfga#configuring-the-server

**When are you going to release?**

**Comment by rhamzeh** [comment]
Thanks for raising the issue @vavsab. It's currently blocked until this [PR](https://github.com/openfga/openfga/pull/125) is merged, but that should be happening soon. Expect `v0.1.5` to be out soon.

**Comment by jon-whit** [comment]
@vavsab we're releasing `v0.1.5` this morning. Sorry for the delay. See #128 . Once that's merged we'll tag and release. I'll close this once it's been released 👍

**Comment by jon-whit** [comment]
See https://github.com/openfga/openfga/releases/tag/v0.1.5.

Closing this now that it's been released. Let us know if you find anything problematic 👍

**Comment by vavsab** [comment]
Wow man! You are working at the speed of light! Thanks a lot

**Comment by rhamzeh** [comment]
Sorry @vavsab, we had an issue in our `v0.1.5` release preventing it from running. We'll be releasing `v0.1.6` with that resolved in a few.

**Comment by vavsab** [comment]
Thanks. Just was wondering why it's failing to start

**Comment by rhamzeh** [comment]
@vavsab [v0.1.6](https://github.com/orgs/openfga/discussions/14) is now out
