### ISSUE TITLE
Make ReadAuthorizationModels faster for Postgres and MySQL

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1256]
https://github.com/openfga/openfga/blob/164963facc61241e1378d8fefb6632c700407163/pkg/storage/mysql/mysql.go#L394-L408

https://github.com/openfga/openfga/blob/164963facc61241e1378d8fefb6632c700407163/pkg/storage/postgres/postgres.go#L409-L421

**Comment by jon-whit** [comment]
This work is superseded by the changes we're introducing for single-row models which is coming very soon. For that reason I'd recommend we close this and prioritize the next-gen instead of this.

**Comment by miparnisari** [comment]
@jon-whit this issue is about ReadAuthorizationModels (plural). I don't see how the work you mention is related

**Comment by jon-whit** [comment]
@miparnisari the code snippets above appear to refer to code specific to our current design of storing models across multiple rows and hence we delegate to `ReadAuthorizationModel` per model id. My point is that if we store one model per row, then this work becomes simply `SELECT * FROM authorization_model WHERE store_id=<id>` and this concurrent fetching is irrelevant.

**Comment by miparnisari** [comment]
@jon-whit ohhhh I understand. Yes you are correct. Closing this in favor of https://github.com/openfga/openfga/issues/1025
