### ISSUE TITLE
Error when trying to save the directly pasted authorization models using openfga playground

### ISSUE THREAD

**Issue by ruppo-912116** [openfga/openfga#1275]
**Summary**
I ran the docker compose for openfga locally and was fiddling around on the playground. On pasting the authorization model and saving it says `Something went wrong! Error saving types, try again later:` and thus it cannot be saved. I am only able to save if I edit the already successfully saved authorization model but cannot save on clearing everything and pasting directly.

- Steps to reproduce
- Navigate to the playground
- remove the current authorization model and paste a simple authorization model and try saving

My docker compose file:

```docker
  migrate:
    depends_on:
      postgres:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:example@postgres:5432/openfga?sslmode=disable
    command: migrate
    networks:
      - backend

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:example@postgres:5432/openfga?sslmode=disable
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=100 
      - OPENFGA_LOG_FORMAT=json # this is added to docker compose
      - OPENFGA_PLAYGROUND_ENABLED=true
    networks:
      - backend
    ports:
      - "8090:8080" #http
      - "8081:8081" #grpc
      - "4000:3000" #playground
      - "2112:2112" #prometheus metrics
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=openfga:8081"]
      interval: 5s
      timeout: 30s
      retries: 3

```

**My authorization model**
```
model
  schema 1.1
  
type user

```

Screenshot

![image](https://github.com/openfga/openfga/assets/84317977/8015a5a1-a743-4844-b7b3-86f4647977ba)|

**Comment by rhamzeh** [comment]
Hi @ruppo-912116 - from the screenshot it looks like you had not created a store first, can you try that before pasting in and saving the model please?

Sorry for the confusing UI, we're planning to fix that

**Comment by ruppo-912116** [comment]
I ran the docker compose and used the openfga api endpoints
POST http://localhost/8090/stores with request body 
```
{
 name; "test-store"
}
```
I got 200 status code with id, name, createdAt and updatedAt response.
 Does the playground use that store as default?

**Comment by rhamzeh** [comment]
If your API is at port 8090, make sure you are setting the `OPENFGA_HTTP_PORT` and not just changing the port in docker, otherwise the Playground will not know that the port is changed.

See https://github.com/openfga/openfga/issues/1001#issuecomment-1739960688

**Comment by adriantam** [comment]
@ruppo-912116 do you still see this problem?  If not, maybe we can close this issue?  Thank you.

**Comment by ruppo-912116** [comment]
Yes, we can close the issue.

**Comment by sashokbg** [comment]
Thanks to @ruppo-912116 the issue is resolved for me too:

```
curl -X POST http://localhost:8080/stores -d '{"name": "test-store"}'
```
