### ISSUE TITLE
Add support for limiting OIDC clients to specific subjects or other claim data

### ISSUE THREAD

**Issue by evankanderson** [openfga/openfga#1282]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

We would like to limit which clients may query OpenFGA while using the k8s OIDC issuer (for k8s service accounts).

Our current use case only need to be an on/off access control, but I can imagine wanting to limit Checks (by `relation` or `object`), Expands (by type), and Writes (by `relation` and `object`) to different subjects.

### Describe the ideal solution

For now, a config option `authn.oidc.allowedSubjects` or `authn.oidc.subjects[name]` --> wildcarded methods would be ideal.

### Alternatives and current workarounds

We can limit access to the OpenFGA server using NetworkPolicy (or a service mesh if we were using one).

### Additional context

I'm not sure what the long-term goals here are, but I'd be willing to do a simple change for the config option here.

**Comment by aaguiarz** [comment]
Hi @evankanderson 

The solution we are thinking would allow you to everything you are describing but it's more complex than adding a list of subjects.

We are thinking of having more [flexible authorization options](https://github.com/openfga/roadmap/issues/30) for defining client permissions on top of [Modules](https://github.com/openfga/roadmap/issues/39). 

e.g. we'd have a model like this that you can use to decide the specific permission each client has per module:

```
model
  schema 1.1

type client
    
type module
  relations

    define tuple_viewer : [client] or tuple_writer 
    define tuple_writer : [client] 

    define model_viewer : [client] or model_writer
    define model_writer : [client]
    
    define can_call_check : [client] or tuple_viewer 
    define can_call_list_objects: [client] or tuple_viewer 
    define can_call_read:  [client] or tuple_viewer 
    define can_call_expand: [client] or tuple_viewer 
    
    define can_call_read_model: [client] or model_viewer 
    
    define can_call_write: [client] or tuple_writer 
    define can_call_write_model:  [client] or model_writer 
```

Makes sense? Do you think that would work for your use case?

**Comment by evankanderson** [comment]
That does look reasonable; is there an expected timeline for that feature?

Our need isn't urgent at the moment, but I do prefer in-band authorization over network policy as my first tool for access control.  😁

**Comment by aaguiarz** [comment]
We'll be starting working on that problem by the end of the month. We'll do the 'modular models' piece first and the authorization piece next.

Another approach some customers are following is proxying calls to OpenFGA somehow (e.g. a gateway) and add the authorization logic there (e.g. inspect the check request and only allow certain requests depending on the client).

**Comment by miparnisari** [comment]
> For now, a config option authn.oidc.allowedSubjects or authn.oidc.subjects[name] --> wildcarded methods would be ideal.

Hey @evankanderson! We implemented the flag `OPENFGA_AUTHN_OIDC_SUBJECTS` in version 1.5.8 😄 it doesn't support wildcards though.

**Comment by miparnisari** [comment]
Closing as implemented, feel free to reopen.
