### ISSUE TITLE
Add dimension on request_duration_by_query_count_ms on whether model is served from cache

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#1289]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

As operator, we will need to distinguish whether check latency is large due to time use for looking up authmodel ID.  

### Describe the ideal solution

The measurement `request_duration_by_query_count_ms` has dimension on whether model is served from cache. 

### Alternatives and current workarounds

1. Dimension on whether auth model ID is provided - as discussed below, this also provides what we need.  However, it does not allow detail on whether model is served from cache.
2. Dimension on number of DB required to look up model - also accomplish what we want, but this could lead to large cardinality in measurement

**Comment by miparnisari** [comment]
> check latency is large due to time use for looking up latest auth model ID.

Finding the latest model involves at most two datastore reads:
- One to FindLatestAuthorizationModelID
- One to ReadAuthorizationModel

I expect this will only be a concern for Check calls that include very few reads of tuples. In every other case where the majority of the I/O is spent reading tuples, reading the latest model should have very little impact.

**Comment by jon-whit** [comment]
> Finding the latest model involves at most two datastore reads:

> One to FindLatestAuthorizationModelID
> One to ReadAuthorizationModel

Practically speaking, there isn't any reason why this has to be the case, and in fact, we should change that for performance reasons. Looking up and fetching the latest authorization model should be an O(1) operation not O(2). If a model is stored as a single row, then a simple column indicating `latest` would suffice to serve a single lookup.

**Comment by miparnisari** [comment]
Agree, we can open a separate issue for that. It will be a breaking change but we can do it.

> Looking up and fetching the latest authorization model should be an O(1) operation not O(2)

Nitpick: O(2) == O(1) :) but yeah 1 read is better than 2 for sure.

**Comment by adriantam** [comment]
Updated issue description to add dimension based on # of DB lookup for model instead of whether auth model is provided in original request

**Comment by adriantam** [comment]
Split the work with regards to 1 vs. 2 db lookup in https://github.com/openfga/openfga/issues/1382
