### ISSUE TITLE
Update `openfga/language` Go module for DSL transformer/parser and refactor usages

### ISSUE THREAD

**Issue by jon-whit** [openfga/openfga#1302]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

A lot of our tests today use the openfga/language parser for Go to make it easier to write tests using our DSL syntax instead of the JSON model syntax. You can see a few examples of this here:

https://github.com/openfga/openfga/blob/main/internal/graph/check_test.go#L43-L55
https://github.com/openfga/openfga/blob/main/internal/graph/cached_resolver_test.go#L449-L469
https://github.com/openfga/openfga/blob/main/pkg/server/server_test.go#L182-L188

A more recent commit/release of the parser supports whitespace better, and so we can refactor these usages to have better usage of whitespace in the test files. The existing tests today had to swallow whitespace to avoid parser errors, and so they read quite cryptically relative to the other whitespace in the file.

### Describe the ideal solution

Upgrade the parser and fix any of the whitespace in the tests that use the parser to parse a DSL model string.

**Comment by professorabhay** [comment]
Hey, @jon-whit ! I would like to work on this.

**Comment by jon-whit** [comment]
@professorabhay awesome! We look forward to the contribution. That will make our lifes as maintainers a little bit nicer when writing tests in the future. Thank you!

**Comment by professorabhay** [comment]
Sure @jon-whit, I'll gonna do my best. Just want to ask a question to understand things clearly.
As mentioned to update `openfga/language`  Go module, Do I have to make changes in the files of this `https://github.com/openfga/language`?

**Comment by 7h3-3mp7y-m4n** [comment]
is the issue is on progress if not then I'll like to work on it

**Comment by miparnisari** [comment]
> Do I have to make changes in the files of this https://github.com/openfga/language?

@professorabhay no, that shouldn't be necessary.

**Comment by 7h3-3mp7y-m4n** [comment]
Hey there , If the issue is stale then I would like to try my hands on this , Thanks :)

**Comment by rhamzeh** [comment]
@professorabhay how are things going? If you have decided not to work on this task, please do let us know.

If you are still working on it, I would encourage you to open a Draft PR as that will help us see your progress and other folks to provide valuable feedback

**Comment by rhamzeh** [comment]
Hi @professorabhay - there's these comments from @miparnisari and @jon-whit 

https://github.com/openfga/openfga/pull/1339#issuecomment-1927344675
https://github.com/openfga/openfga/pull/1339#issuecomment-1936293178

As Jon mentioned, start with focusing on pkg/server and internal to narrow down scope. You can use the regex maria shared to help you find what you are looking for in those folders

**Comment by 00chorch** [comment]
Hi @jon-whit / @miparnisari, happy Friday.

Knowing it is low priority, I'm still blocked with one workflow check: `Pull Request / lint (pull_request)` of my PR #1620 

Tests keep failing and I can't reproduce locally to troubleshoot.

Whenever possible, any guidance is welcomed.

**Comment by 00chorch** [comment]
Happy Friday folks,
found a workaround for flaky tests and PR #1620 is ready for review

**Comment by 00chorch** [comment]
Hi @jon-whit @miparnisari & rest of the team
this indentation PR #1654  is ready and includes the indentation for tests inside "pkg/server" and "internal".

If desired, I can add tests in other folders. I was avoiding that to avoid PR to have too many files.
Let me know if you prefer to review this way -incrementally-, or if I should add other indented files too here

Thanks for your time reviewing.

**Comment by 00chorch** [comment]
Hi there,
the PRs #1654 , #1694 , and #1696 are ready for review and will fully resolve this issue.

**Comment by jpadilla** [comment]
Thanks @00chorch!
