### ISSUE TITLE
Support ISO8601 time format in JSON logs.

### ISSUE THREAD

**Issue by raj-saxena** [openfga/openfga#1326]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

We are running OpenFGA in our Kubernetes cluster using the helm-chart. There are 2 logging formats that are supported - `text` and `json` and [it is advised](https://github.com/openfga/helm-charts/blob/d3f80da94057b294570f1a2b314f760ac8ca9bd0/charts/openfga/values.schema.json#L287) to use `json` for `production`. 

The default timestamp format for `json` is Unix time format i.e., the number of _seconds_ since Epoch (Example - `1706609988.788818`).
<img width="1512" alt="image" src="https://github.com/openfga/openfga/assets/6253803/0b34d6a5-fdfd-4f8f-bbf0-90cc6998decc">

However, the issue is that [Datadog expects ](https://docs.datadoghq.com/logs/guide/logs-not-showing-expected-timestamp/#supported-date-formats)_milliseconds_ for this format. 
<img width="874" alt="image" src="https://github.com/openfga/openfga/assets/6253803/c555286c-d85e-4571-82a5-3b041494daa6">
I have been working with their support and also found [this issue ](https://github.com/DataDog/datadog-agent/issues/3926) that confirms the limitation.

There's no easy way to fix it in Datadog and without this, the logs don't seem to be ingested in their system. Since Datadog is a big enough observability platform, I come to you to propose a possible solution.

### Describe the ideal solution

I see that the [`text` log format supports `ISO8601` as timestamp format](https://github.com/openfga/openfga/blob/ad04038afbd58890cb65b409780b0cbbf85d5103/pkg/logger/logger.go#L125-L129)
However, I can't use them for my purposed because of the weird format of the generated logs. 
<img width="1501" alt="image" src="https://github.com/openfga/openfga/assets/6253803/b3cfef33-6fab-4d26-8aeb-87ea9a30e6cc"> 
(By weird, I mean the color and the json-in-text that breaks parsing)
<img width="729" alt="image" src="https://github.com/openfga/openfga/assets/6253803/66b2a080-a1a0-4fee-9042-1154386c7626">

The simplest solution seems like either:
1. Make `zapcore.ISO8601TimeEncoder` as a common format for both json and text by moving it out of [the if block here](https://github.com/openfga/openfga/blob/ad04038afbd58890cb65b409780b0cbbf85d5103/pkg/logger/logger.go#L125). Or
2. Have a way to specify the timestamp format for the json logs.

I am happy to raise a PR too if you can guide me.

**Comment by jon-whit** [comment]
ISO8601 would be a lot more friendly to the developer anyways. Happy to accept a PR for the contribution. @raj-saxena do you mind submitting a PR to make that the default please?
