### ISSUE TITLE
is it possible to use playground with auth?

### ISSUE THREAD

**Issue by vavsab** [openfga/openfga#133]
Is it possible to make playground work with enabled auth?
I'm using preshared keys but [playground is not aware of it](https://github.com/openfga/openfga/blob/e07a89823f049be029f5f4f8551d1feb65d649ff/assets/playground/index.html).

I just get missing token exception on every request
![image](https://user-images.githubusercontent.com/10233442/181526525-06f7c480-4d04-4e59-aa08-a8fc7a400575.png)

**Comment by jon-whit** [comment]
👋 @vavsab at this time we do not support the embedded Playground with authentication.

We do have on our roadmap a plan to add an authentication input field (or something similar) to allow you to provide a bearer token in the Playground UI. That work will likely be part of a larger effort to open-source the OpenFGA Playground source code though. We will keep you updated with these developments as they unfold.

**Comment by jon-whit** [comment]
@vavsab we now have support for preshared key authentication in the OpenFGA embedded Playground. If you pull down the main branch it's supported. It will be included in our next most release. I'm closing this now that it's supported. If you find any issues with it, please don't hesitate to reach back out 👍

**Comment by vavsab** [comment]
Thanks a lot 🥰

**Comment by ldigiuseppe** [comment]
Any chance playground will be integrated with OIDC any time soon?
