### ISSUE TITLE
Release migration feature

### ISSUE THREAD

**Issue by vavsab** [openfga/openfga#134]
Hi team. Is it possible to release this feature?
https://github.com/openfga/openfga/commit/b7d987f12a5e8f093a7eefa52bfddea349c9f966
I'm waiting for it to deploy to my production

**Comment by rhamzeh** [comment]
Thanks for your feedback @vavsab! It will go out in the upcoming `v0.1.7` release, we will try to get out a small release out with this change today.

**Comment by vavsab** [comment]
Take your time. [Made a fork](https://hub.docker.com/r/mapped/openfga) to unblock myself. Thanks for the nice migration feature!

**Comment by rhamzeh** [comment]
@vavsab [v0.1.7](https://github.com/orgs/openfga/discussions/15) that was released last Friday now includes this feature. Thank you for being patient with us!

**Comment by vavsab** [comment]
@rhamzeh  Thanks. Already switched and using it. Works good
