### ISSUE TITLE
Refactor logger.NewLogger with options builder pattern

### ISSUE THREAD

**Issue by jon-whit** [openfga/openfga#1355]
We should refactor the [logger.NewLogger](https://pkg.go.dev/github.com/openfga/openfga@v1.4.3/pkg/logger#NewLogger) signature to use the options builder pattern and if an option is not provided we just default it.

For example,
```go
NewLogger(
  WithFormat("text"),
  WithLevel("info"),
  WithTimestampFormat("ISO8601"),
)
```

_Originally posted by @jon-whit in https://github.com/openfga/openfga/pull/1330#discussion_r1484561151_

**Comment by professorabhay** [comment]
Hey, @jon-whit! I would like to give it a try.
