### ISSUE TITLE
Convert between the API Syntax and the friendly DSL in SDK

### ISSUE THREAD

**Issue by rytsh** [openfga/openfga#1358]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

I want to make everything with using SDK of the openfga but I see there is missing point here.
Documentation declaring us to use CLI for converting DSL to API syntax and even we cannot import CLI to do that so just binary.

Could you also add DSL <-> API conversion in the SDK?

### Describe the ideal solution

CLI tool exist code, same thing in SDK would be solve.

**Comment by rytsh** [comment]
I realized after that this repo https://github.com/openfga/language

**Comment by aaguiarz** [comment]
@rytsh yes, that repo has bindings for Go, Javascript and Java is in the works.

Which language do you want to use?

**Comment by aaguiarz** [comment]
Also, how are you planning to use them?

**Comment by rytsh** [comment]
I use with Go.
I am creating a simple web-ui which can modify tuples also create new stores and anything.
First I thought playground would be good but it has limitation and I need an extra database table to record preferred-usernames and alias of the user to get an ID and use in tuples. After that I make query using authentication token's data.

**Comment by rytsh** [comment]
@aaguiarz  I successfully worked with language repo to make conversion, closing this one thanks.
