### ISSUE TITLE
Add API to read latest authorization model

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#1382]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

API request to get latest authorization model.  Currently, there is something similar when we have [ReadAuthorizationModels](https://openfga.dev/api/service#/Authorization%20Models/ReadAuthorizationModels) and specify page size to 1.  However, the problem is that if you don't specify authorization model ID in check/list objects request etc., two separate DB requests are needed (1 to read latest authorization model ID and 1 to look up the authorization model itself).   

### Describe the ideal solution

Ideally, only 1 DB lookup is needed to get latest authorization model.

### Alternatives and current workarounds

For [ReadAuthorizationModels](https://openfga.dev/api/service#/Authorization%20Models/ReadAuthorizationModels), specify page size = 1.

### Additional context

Split from https://github.com/openfga/openfga/issues/1289

**Comment by miparnisari** [comment]
@adriantam i worked on a `command` to do this here https://github.com/openfga/openfga/pull/1258. Can you please review that and possibly reuse the code from there? it's unit tested, too.

**Comment by adriantam** [comment]
Close this issue for now as we do not want to increase API interface
