### ISSUE TITLE
`no entrypoints defined` error when saving a valid model

### ISSUE THREAD

**Issue by aaguiarz** [openfga/openfga#1385]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [Discord](https://discord.gg/8naAwJfWN6) community and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

When I try to save a valid model I get 

`"error":"the definition of relation 'can_enable_logging' in object type 'entity' is invalid: no entrypoints defined"`

If I delete the `can_enable_logging` relation or if I remove the `but not` from the `has_access_to_logging` relation 

### Expectation

It should not return an error.

### Reproduction

1. Try to save the model  or run `fga model validate --file model.fga`
2. It returns
```
{
  "is_valid":false,
  "error":"the definition of relation 'can_enable_logging' in object type 'entity' is invalid: no entrypoints defined"
}
```

### Store data

```
model
  schema 1.1

type user

type entity
  relations
    define member : [user] 

    define contextual_user: [user]
    define contextual_member : member and contextual_user

    define has_logging_product: [entity]
    define block_logging : [user] and contextual_user

    # If you don't include the "But not", the model validates
    define has_access_to_logging : contextual_member from has_logging_product but not block_logging from has_logging_product

    # If you comment this line, the model validates
    define can_enable_logging : has_access_to_logging

```

### OpenFGA version

Latest version of the CLI

### How are you running OpenFGA?

As a binary

### What datastore are you using?

In-Memory

### OpenFGA Flags

no

**Comment by jon-whit** [comment]
May be related - https://github.com/openfga/openfga/issues/1260
