### ISSUE TITLE
Update `golang-jwt/jwt`

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1396]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

`github.com/golang-jwt/jwt/v4` is old.

### Describe the ideal solution

Update to `github.com/golang-jwt/jwt/v5` as per https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md.

Ideally, https://github.com/openfga/openfga/issues/1395 is done before this task is attempted.

**Comment by ilaleksin** [comment]
Hey @miparnisari , I prepared a PR with the golang-jwt upgrade to v5

please review these changes

**Comment by miparnisari** [comment]
Pending:
1. Update to `MicahParks/keyfunc@v3`
2. Perform all the JWT validations in  one pass to simplify the code

**Comment by miparnisari** [comment]
Resolving in favor of https://github.com/openfga/openfga/issues/1827
