### ISSUE TITLE
`hasEntrypoints` code is hard to understand

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1426]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

As seen in https://github.com/openfga/openfga/pull/1422, `typesystem.hasEntrypoints` code is hard to understand. It is currently trying to find all terminal users of a given relation, but the way it does it is too complicated. 

Also, `typesystem.HasCycles` and `typesystem.hasEntrypoints` have duplicate code: they are both trying to find if there is a cycle as defined by "all paths in the cycle are computed usersets".

### Describe the ideal solution

two changes:

1. `hasEntrypoints(type,relation)` would be more readable if it were written like this:
 - build the graph of the model
 - start at the node `type#relation` and traverse the graph in DFS fashion
 - if during the traversal one of the nodes is a terminal user, return true

2. in model validation, change the order of the validations to
- first `HasCycles`
- then `hasEntrypoints`

**Comment by rhamzeh** [comment]
I would not prioritize this, as we're focusing on moving this logic to the language package (https://github.com/openfga/language/issues/99)
