### ISSUE TITLE
ListUsers API

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1428]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

https://github.com/openfga/roadmap/issues/16

### Describe the ideal solution

New ListUsers and StreamingListUsers API

**Comment by meldsza** [comment]
Will be fixed by: #1433 
(just tagging it because I see that it is not tagged here)
