### ISSUE TITLE
Authorization Model not found

### ISSUE THREAD

**Issue by vfarcic** [openfga/openfga#1431]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

It seems that writing tuples randomly fails with the `Authorization Model not found` message.

### Expectation

It always works.

### Reproduction

Take a look at the output of executing the same command 3 times.

```sh
$ fga tuple write --store-id $FGA_STORE_ID \
    --model-id $FGA_MODEL_ID user:vfarcic owner document:Z

Error: failed to write tuple: Write validation error for POST Write with body {"code":"authorization_model_not_found","message":"Authorization Model '01HREZ3T0XGGGBMSW8S5HJP90A' not found"}
 with error code authorization_model_not_found error message: Authorization Model '01HREZ3T0XGGGBMSW8S5HJP90A' not found

$ fga tuple write --store-id $FGA_STORE_ID \
    --model-id $FGA_MODEL_ID user:vfarcic owner document:Z

Error: failed to write tuple: Write validation error for POST Write with body {"code":"authorization_model_not_found","message":"Authorization Model '01HREZ3T0XGGGBMSW8S5HJP90A' not found"}
 with error code authorization_model_not_found error message: Authorization Model '01HREZ3T0XGGGBMSW8S5HJP90A' not found

$ fga tuple write --store-id $FGA_STORE_ID \
    --model-id $FGA_MODEL_ID user:vfarcic owner document:Z

{
  "successful": [
    {
      "object":"document:Z",
      "relation":"owner",
      "user":"user:vfarcic"
    }
  ]
}
```

### Store data

```json
{
    "schema_version": "1.1",
    "type_definitions": [
        { "type": "user" },
        {
            "type": "document",
            "relations": {
                "reader": { "this": {} },
                "writer": { "this": {} },
                "owner": { "this": {} }
            },
            "metadata": {
                "relations": {
                    "reader": { "directly_related_user_types": [ { "type": "user" } ] },
                    "writer": { "directly_related_user_types": [ { "type": "user" } ] },
                    "owner": { "directly_related_user_types": [ { "type": "user" } ] }
                }
            }
        }
    ]
}
```

### OpenFGA version

fga version v`0.2.6` (commit: `dc4e39648ec5b626fc5c44c4f9f77a1e15806ab7`, date: `2024-02-28T12:47:25Z`)

### How are you running OpenFGA?

In Kubernetes

### What datastore are you using?

In-Memory

### OpenFGA Flags

No

**Comment by rhamzeh** [comment]
Thanks @vfarcic, we'll taking a look!

**Comment by adriantam** [comment]
Thanks for reporting @vfarcic, can you provide us with the following info?

1. Can you run the following command to help us isolate whether the CLI can find any authorization model ID?
```
fga model list --store-id=$FGA_STORE_ID 
``` 

2. Can you provide us with the version of openfga?  0.2.6 seems to refer to the version of [CLI](https://github.com/openfga/cli).  It will be good to have the version of openfga [itself](https://github.com/openfga/openfga).  We will expect the version to be 1.x.x.

**Comment by vfarcic** [comment]
```sh
fga model list --store-id=$FGA_STORE_ID
```

```json
{
  "authorization_models": [
    {
      "id":"01HREZ3T0XGGGBMSW8S5HJP90A",
      "created_at":"2024-03-08T12:02:56Z"
    }
  ]
}
```

The image I'm using is `openfga/openfga:v1.5.0`.

OpenFGA is deployed as a Helm chart with default values except for Ingress.

```sh
cat values.yaml
```

```yaml
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: openfga.35.229.65.41.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
```

**Comment by jpadilla** [comment]
@vfarcic i think what's happening here is that by default our helm chart uses 3 replicas, which doesn't really translate when using the in memory datastore. Specify `replicaCount: 1` in your `values.yaml` and try again.

**Comment by vfarcic** [comment]
That's it. Thanks a ton.
