### ISSUE TITLE
authn oidc missing in openfga/openfga:v1.5

### ISSUE THREAD

**Issue by tafaust** [openfga/openfga#1434]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

The error message I received:
```
panic: the playground only supports authn methods 'none' and 'preshared'

goroutine 1 [running]:
github.com/openfga/openfga/cmd/run.run(0xc00009b600?, {0x1e111c0?, 0x4?, 0x1287dbd?})
        /home/runner/work/openfga/openfga/cmd/run/run.go:271 +0x10e
github.com/spf13/cobra.(*Command).execute(0xc0002aac00, {0x1e111c0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002aa900)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0002aa900?)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
        /home/runner/work/openfga/openfga/cmd/openfga/main.go:28 +0x12f
```

### Expectation

I expect no error message

### Reproduction

I followed https://openfga.dev/docs/getting-started/setup-openfga/docker#oidc-authentication without TLS. I have OpenFGA running behind a traefik3 reverse proxy.

### OpenFGA version

v1.5

### How are you running OpenFGA?

In Docker

### What datastore are you using?

Postgres

### OpenFGA Flags

none

### Logs

See the description.

**Comment by aaguiarz** [comment]
Hi @tafaust 

You'll need to disable the playground if you configure OIDC authentication:

`openfga run --playground-enabled=false`

We don't have a way to get a token from the OIDC server and send it to the OpenFGA backend from the Playground.

You can use the [CLI](https://github.com/openfga/cli) to interact with an OpenFGA service and the [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=openfga.openfga-vscode) to edit models / tuples, to use OpenFGA with a similar experience than the Playground. 

The CLI can obtain a token from the OIDC server.

Let me know if it helps

**Comment by tafaust** [comment]
Hi @aaguiarz,
Thanks for your fast response! That solved it. Is there a UI to build the user permissions?

**Comment by aaguiarz** [comment]
@tafaust you mean for the end-users or admins to manage permissions? No, there's not. You'd need to build it and use the FGA API to reflect those changes.

For developers, the idea is that they use the CLI + VS Code + .fga.yaml files for testing.
