### ISSUE TITLE
Log all server settings/flags

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1501]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

When server starts, print out all server settings.

### Describe the ideal solution

A log of all server settings, including defaults and non-defaults. For example:

```go
func PrintJSON(obj interface{}, logger logger.Logger) {
	bytes, _ := json.Marshal(obj)
	logger.Info(string(bytes))
}
func (s *ServerContext) Run(ctx context.Context, config *serverconfig.Config) error {
	PrintJSON(config, s.Logger)
    // ...
```

We also should **not** log confidential settings like the keys if using pre-shared key authentication

**Comment by jon-whit** [comment]
Also adding this log output as a recommended field to include in the Bug report in our Github issue templates 👍 Having this information can help us better troubleshoot community reported issues quickly.
