### ISSUE TITLE
with error code validation_error error message: modular models (schema version 1.2) are not supported

### ISSUE THREAD

**Issue by xuanlongvts** [openfga/openfga#1524]
### Checklist

- [ ] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [ ] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [ ] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [ ] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [ ] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [ ] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

when i run:  fga model write --store-id=$FGA_STORE_ID --file fga.mod

this is the tutorial: https://openfga.dev/docs/modeling/modular-models

Then, it happ:  with error code validation_error error message: modular models (schema version 1.2) are not supported

### Expectation

I think it genegrated  a dsl file

### Reproduction

https://github.com/xuanlongvts/authen-autho/tree/main/open-fga/16_modular_models

### OpenFGA version

latest

### How are you running OpenFGA?

As a binary

### What datastore are you using?

In-Memory

### OpenFGA Flags

fga model write --store-id=$FGA_STORE_ID --file fga.mod

### Logs

Error: failed to write model due to WriteAuthorizationModel validation error for POST WriteAuthorizationModel with body {"code":"validation_error","message":"modular models (schema version 1.2) are not supported"}
 with error code validation_error error message: modular models (schema version 1.2) are not supported

**Comment by rhamzeh** [comment]
As of v1.5.2, support for schema 1.2 is still experimental and you need to run the server with the following flag to enable it: 
`OPENFGA_EXPERIMENTALS=enable-modular-models`

See the release notes: https://github.com/openfga/openfga/releases/tag/v1.5.1
