### ISSUE TITLE
Add panic recovery middleware

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1542]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

For scenarios such as https://github.com/openfga/openfga/pull/1517, where the server panics abruptly.

### Describe the ideal solution

We should add a panic recovery middleware for both unary and streaming APIs: https://github.com/openfga/openfga/blob/b2fdf4b73e14977c5e199f86124813f84f507413/cmd/run/run.go#L376-L394

It should be the first handler in the chain.

**Comment by Siddhant-K-code** [comment]
The code you pointed above can handle the gRPC case. But, do you think, we would also require need to handle the HTTP case here:

https://github.com/openfga/openfga/blob/b2fdf4b73e14977c5e199f86124813f84f507413/cmd/run/run.go#L574-L583


Something like this:

```go
httpServer := &http.Server{
    Addr: config.HTTP.Addr,
    Handler: panicRecoveryMiddleware(cors.New(cors.Options{
        AllowedOrigins:   config.HTTP.CORSAllowedOrigins,
        AllowCredentials: true,
        AllowedHeaders:   config.HTTP.CORSAllowedHeaders,
        AllowedMethods: []string{
            http.MethodGet, http.MethodPost,
            http.MethodHead, http.MethodPatch,
            http.MethodDelete, http.MethodPut,
        },
    }).Handler(mux), s.Logger), // Wrap the existing CORS handler with the panic recovery middleware
}
```


And, our panic recovery function (which wraps an `http.Handler` and recovers from any panics, logging the error and returning an HTTP 500 status.) could be something like the following:

```go
func panicRecoveryMiddleware(next http.Handler, logger logger.Logger) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        defer func() {
            if err := recover(); err != nil {
                logger.Error(fmt.Sprintf("Recovered from panic: %v", err))
                http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
            }
        }()
        next.ServeHTTP(w, r)
    })
}
```

**Comment by Siddhant-K-code** [comment]
btw, fix regarding gRPC, i kind of the find the fix and i am still not comfortable to write tests for the same, that's why, hesitant to raise the PR. Changes i can think of that can fix this:

```go
// UnaryPanicRecoveryInterceptor recovers from panics in unary handlers
func UnaryPanicRecoveryInterceptor(logger logger.Logger) grpc.UnaryServerInterceptor {
	return func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
		defer func() {
			if r := recover(); r != nil {
				logger.Error("Recovered from panic in unary RPC", zap.String("panic_info", r.(string)))
				panic(r) // re-panic to let the grpc server handle the error
			}
		}()
		return handler(ctx, req)
	}
}
```

```go
// StreamPanicRecoveryInterceptor recovers from panics in stream handlers
func StreamPanicRecoveryInterceptor(logger logger.Logger) grpc.StreamServerInterceptor {
	return func(srv interface{}, stream grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) error {
		defer func() {
			if r := recover(); r != nil {
				logger.Error("Recovered from panic in stream RPC", zap.String("panic_info", r.(string)))
				panic(r)
			}
		}()
		return handler(srv, stream)
	}
}
```

**Comment by miparnisari** [comment]
> The code you pointed above can handle the gRPC case

Our current code in `main` can't :( From my quick test, an artificially introduced panic in Check API will crash the service.

Adding simply `grpc_recovery.UnaryServerInterceptor()` will not crash the server but nothing will be logged.

Adding something like 

```go
[]grpc.UnaryServerInterceptor{
				grpc_recovery.UnaryServerInterceptor(grpc_recovery.WithRecoveryHandlerContext(func(ctx context.Context, p interface{}) (err error) {
					s.Logger.Error("Recovered from panic RPC", zap.Any("panic_info", p))
					return status.Errorf(codes.Unknown, "internal error")
				})),
```

will log 😄

**Comment by Siddhant-K-code** [comment]
Thanks @miparnisari for the explanation ❤️
