### ISSUE TITLE
Replace `github.com/hashicorp/go-multierror` with `errors.Join`

### ISSUE THREAD

**Issue by sergiught** [openfga/openfga#1556]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

In the latest versions of Go, specifically from Go 1.19 onwards, we can use the `errors.Join` function, which was added to the standard library. This function can replace all of the functionality of the 3rd party [hashicorp/go-multierror](github.com/hashicorp/go-multierror) package.

### Describe the ideal solution

The `errors.Join` function in Go allows you to combine multiple errors into a single error. If all errors are nil, `errors.Join` returns nil. If only one error is non-nil, it returns that error. If there are multiple non-nil errors, it returns an error that formats as the concatenation of the individual errors' messages.

Example:

```go
    err1 := errors.New("error one")
    err2 := nil
    err3 := errors.New("error three")

    joinedErr := errors.Join(err1, err2, err3)
    if joinedErr != nil {
        fmt.Println(joinedErr) // Output: error one; error three
    }
```

### Additional context

- https://pkg.go.dev/errors#Join

**Comment by c0d33ngr** [comment]
I'll love to work on this
