### ISSUE TITLE
SQL Error: Context canceled

### ISSUE THREAD

**Issue by ruppo-912116** [openfga/openfga#1570]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

When carrying out openfga write operation for a tuple, I am getting this issue.  I am using docker to run the openfga service.

### Expectation

The write operation should have been successful. The write operations are successful most of the times because all the client configurations are correct. This issue is seen on interval i.e. in few days. It goes away on rerunning the container and this issue will reoccur after few days.

### Reproduction

I don't have any steps to reproduce...

### Store data

I cannot provide this information, sorry.

Tuple

```
{"tuple_keys":[{"user":"user:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","relation":"owner","object":"organization:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","condition":null}]}
```

### OpenFGA version

 image: openfga/openfga:latest

### How are you running OpenFGA?

In Docker

### What datastore are you using?

Postgres

### OpenFGA Flags

OPENFGA_LOG_LEVEL: debug; OPENFGA_LOG_FORMAT: text; OPENFGA_PLAYGROUND_ENABLED: "true";OPENFGA_DATASTORE_MAX_OPEN_CONNS: "100"; OPENFGA_PLAYGROUND_ENABLED: "true"

### Logs

```
2024-04-25T06:34:02.543Z	ERROR	rpc error: code = Code(4000) desc = Internal Server Error	{"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "Write", "grpc_type": "unary", "request_id": "xxxx", "user_agent": "Java-http-client/21", "raw_request": {"store_id":"xxxxxxxxx","writes":{"tuple_keys":[{"user":"user:xxxxx","relation":"owner","object":"organization:xxxx","condition":null}]},"deletes":null,"authorization_model_id":"xxxxx"}, "raw_response": {"code":"internal_error","message":"Internal Server Error"}, "authorization_model_id": "xxxx", "peer.address": "127.0.0.1:53268", "store_id": "xxxx", "grpc_code": 4000, "internal_error": "sql error: context canceled"}

```

**Comment by adriantam** [comment]
Error: context canceled usually indicates timeout.  One of the first thing to check is to see if your database is dimensioned correctly (i.e., the CPU, [number of connections](https://www.postgresql.org/docs/current/runtime-config-connection.html) etc.) for your workload.

**Comment by ruppo-912116** [comment]
Hmm... i need to check what happens to the running openfga service if the database goes down since our development server goes down frequently. this issue is rarely present on the staging environment though.
