### ISSUE TITLE
Implement ListRelations as a single network request instead of multiple Check requests

### ISSUE THREAD

**Issue by gurleensethi** [openfga/openfga#1591]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

While investigating the `openfga/go-sdk` source code to address some performance issues, I discovered that the ListRelations function is actually executing multiple parallel Check requests (see [call to BatchCheck](https://github.com/openfga/go-sdk/blob/main/client/client.go#L2140-L2148) and [multiple requests within BatchCheck](https://github.com/openfga/go-sdk/blob/main/client/client.go#L1810-L1835)).

This approach becomes problematic when managing a high number of relations, such as 300, for several reasons:

1. There is a maximum limit on concurrent `Check` requests that can be executed, although this can be mitigated by increasing the `MaxParallelRequests` setting.
2. The substantial overhead from numerous parallel network requests contributes to decreased performance (this is huge).
3. Since all relations involve the same User + Object, each request repeatedly retrieves the corresponding tuple from the database (can be mitigated to some extent by enabling node caching).

![image](https://github.com/openfga/openfga/assets/14363536/f04d1a50-22f2-4ed7-8850-fe089e231570)

### Describe the ideal solution

Ideally, calling `ListRelations` (and even `CheckBatch` for that matter) should result in only a single call to the OpenFGA server, this should help a lot with performance.

![image](https://github.com/openfga/openfga/assets/14363536/57734aa8-c279-49a3-b148-9a808f0cc899)

**Comment by rhamzeh** [comment]
Hi @gurleensethi - thanks for raising this. It's already on our Roadmap: https://github.com/orgs/openfga/projects/1?pane=issue&itemId=28481432
