### ISSUE TITLE
Custom sql error handler for common database operations

### ISSUE THREAD

**Issue by kalleep** [openfga/openfga#1709]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

Hey, we are experimenting with embedding open fga inside Grafana. OpenFGA already have support for Mysql and Postgres datastores but we must support sqlite on top of these. We made a [pr](https://github.com/openfga/openfga/pull/1615) to add sqlite. What I gathered from that is there will probably exist some kind of plugin system in the future where should add sqlite instead of  merging it into main.

This is not a blocker for us because we can just implement this data store directly in Grafana. This was pretty straight forward and it was nice to be able to re-use the [test suite](https://github.com/openfga/openfga/blob/main/pkg/storage/test/storage.go#L29) for stored. The one problem we are facing is `sqlcommon.HandleSQLError`. We need to special case duplication errors from sqlite similar to how it is done for both progres and mysql today. This works fine for most db operations except common operations provided by `sqlcommon` package such as [Write](https://github.com/openfga/openfga/blob/main/pkg/storage/sqlcommon/sqlcommon.go#L330). Here HandleSQLError is called directly and AFAIK there is not way to override the behavior. 

### Describe the ideal solution

It would be good if we could pass a custom error handler `func(err error, args ...any) error` to common database operations provided by this package. For mysql and postgres provided by openFGA this would be `sqlcommon.HandleSQLError`.

### Alternatives and current workarounds

The workaround we have right now is to [copy](https://github.com/grafana/grafana/pull/89486/files#diff-59de55e7bb801b29e7827713f84603133199bba04e4b853f046e34f64c90357eR19) `sqlcommon.Write` function and handle potential errors with out custom handler.

**Comment by kalleep** [comment]
Another much simpler solution would be to not call HandleSQLError from these common functions and do it from stores instead

**Comment by DanCech** [comment]
Should be solved now that #1615 is merged

**Comment by miparnisari** [comment]
@DanCech I think we still haven't addressed the proposed idea:

> It would be good if we could pass a custom error handler `func(err error, args ...any)` error to common database operations provided by this package. For mysql and postgres provided by openFGA this would be sqlcommon.HandleSQLError. 

I think the current `sqlcommon.HandleSQLError` is doing too much
- it handles all the different SQL databases
- it handles errors coming from very different methods (Reads/Writes etc)

I think we need to come up with a code architecture that fixes both problems.

**Comment by DanCech** [comment]
I agree that it does too much and that the individual storage adapters should provide their own handler for specific errors. Technically sqlite could just use its own now because afaik it doesn't call any sqlcommon functions that use HandleSQLError any more.
