### ISSUE TITLE
Store ULID as 128 bits instead of TEXT

### ISSUE THREAD

**Issue by mmrath** [openfga/openfga#179]
I might be missing some context, but just wanted to check anyway. I think it would be efficient to keep 128 bits instead of keeping the string representation. Something like a snowflake id is probably even better.

**Comment by craigpastro** [comment]
Oh my goodness! Sorry for the delay in response.

The reason that we use ulids is that they are sortable (similar to snowflake ids). This is important for our continuations tokens. We have some queries of the form `ulid > someulid`.

Do you know if the byte representation of a ulid is sortable? If so, then yes, this could be a nice optimization.

Thanks for your comment!

**Comment by mmrath** [comment]
Yes the binary representation of ULID are sortable.

**Comment by craigpastro** [comment]
Interesting. Thanks! We'll try to check it out. Or, of course, we welcome PRs!

**Comment by jon-whit** [comment]
Closing this as we do not plan on doing it at the moment. We'll keep it in mind and also resurrect it if any further recommendations related to this pop up, but for now marking as closed.
