### ISSUE TITLE
Remove `emptyTupleIterator`

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1823]
https://github.com/openfga/openfga/blob/07794019d080bf629a6408d9917ea1492e1eaba6/pkg/storage/iterators.go#L36-L50

This code isn't referenced anywhere except in tests, let's remove it.

**Comment by HeetShah** [comment]
I'm happy to take this on as my first ticket. Would be nice to get familiar with how committing/merging PRs work.
