### ISSUE TITLE
Simplify OIDC token validation errors

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1827]
## Problem

The OIDC authenticator can return many different errors:
https://github.com/openfga/openfga/blob/a2df7810d7faf1a34b21e5abecb7472da54b28d3/internal/authn/oidc/oidc.go#L41-L45

I think we shot ourselves in the foot by having all these custom error codes. The code would be much simpler and therefore more secure if we performed all validations in one go:

```go
jwtParser := jwt.NewParser(
		jwt.WithValidMethods([]string{jwt.SigningMethodRS256.Alg()}),
		jwt.WithIssuedAt(),
		jwt.WithExpirationRequired(),
		jwt.WithAudience(config.Audience),
	)
if err != nil  || !token.Valid{
	return nil, errInvalidToken
}
```

_Originally posted by @miparnisari in https://github.com/openfga/openfga/pull/1601#discussion_r1592867588_
            
## Task
- Update to MicahParks/keyfunc@v3
- Perform all the JWT validations in one pass to simplify the code
- Remove all the custom error codes and simply return `invalidClaims` if the token is invalid.

**Comment by ovindu-a** [comment]
Hi @miparnisari @aaguiarz, can I work on this?

**Comment by himanshunanda22** [comment]
hi @miparnisari could you please assign this task to me

**Comment by aaguiarz** [comment]
Thanks @himanshunanda22 , I assigned it to @ovindu-a as he requested it first.

@ovindu-a let me know if you can still work on this

**Comment by ovindu-a** [comment]
Hi @aaguiarz yes I will work on this
