### ISSUE TITLE
Connection closed abruptly because of SIGTERM is not handled.

### ISSUE THREAD

**Issue by flex-seongbok** [openfga/openfga#1910]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

When restarting OpenFGA, our server experiencing forced connection close.
When OpenFGA receives SIGTERM signal it continue processing ongoing requests and shutdown only when nothing left.
SIGTERM should also added to handled signals at [code](https://github.com/openfga/openfga/blob/v1.6.1/cmd/run/run.go#L438)

Kubernetes sends SIGTERM on graceful termination period. [link](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination)
> Typically, with this graceful termination of the pod, kubelet makes requests to the container runtime to attempt to stop the containers in the pod by first sending a TERM (aka. SIGTERM) signal, with a grace period timeout, to the main process in each container.

originally from https://github.com/openfga/openfga/issues/1909

### OpenFGA version

v1.6.0

### How are you running OpenFGA?

In Kubernetes

### What datastore are you using?

MySQL

### OpenFGA Flags

no

### Logs

upstream connect error or disconnect/reset before headers. reset reason: connection termination

dev.openfga.sdk.errors.FgaApiInternalError: check

**Comment by miparnisari** [comment]
👍 Good find @flex-seongbok. Can you send a PR? 😄

**Comment by flex-seongbok** [comment]
> 👍 Good find @flex-seongbok. Can you send a PR? 😄

I would like to do but we are not ready to CCLA for now.
We are preparing CCLA but it will takes some time. sorry.

**Comment by flex-seongbok** [comment]
```go
- ctx, stop := signal.NotifyContext(ctx, os.Interrupt, os.Kill)
+ ctx, stop := signal.NotifyContext(ctx, os.Interrupt, os.Kill, syscall.SIGTERM)
```
@miparnisari Could you apply this?
