### ISSUE TITLE
Provide better ways to clean tuples

### ISSUE THREAD

**Issue by zetaab** [openfga/openfga#1930]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

We have been trying to migrate to openfga in case of our first application. However, we do have quite extensive integration tests and we are reusing like object `id`s. We would like to see better ways to delete tuples from openfga, to "reset" the state before/after single tests. By that way we could have possibility to execute repeatable tests.

I got everything working by using postgresql database behind openfga, and then executing commands to postgresql database itself. However, it is kind of dirty hack. So I propose real api for this.

I am running following code after each test:
```
		_, err = db.Exec("DELETE FROM tuple where object_type = 'document'")
		assert.NoError(t, err)
```

### Describe the ideal solution

Ideally there could be way to delete all tuples related to `object_type`. I am thinking could POST `/stores/{store_id}/write` allow that? by specifying 

```
{
  "deletes": {
    "tuple_keys": [
      {
        "user": "*",
        "relation": "*",
        "object": "document:*"
      }
    ]
  }
}
```

Other possibility is to provide new api that makes it possible to clean data easily from the openfga to make it working better with the tests. Like could there be way to clean all data from the store but keep the store_id?

My use-case is just for `object_type`. However, allowing wildcards in delete tuple_keys could help to make lot of more use-cases.

**Comment by jcchavezs** [comment]
nice to see you around @zetaab

**Comment by zetaab** [comment]
lets say that I have object `document:1` when someone goes to rest api and will delete that from application. I would like to clean all tuples related `document:1`. Currently its not easily possible? Or is it even possible to list all relations (and users) to object?

**Comment by jpadilla** [comment]
@zetaab could you potentially use the Read API followed by batches to the Write API to delete?

POST /stores/{store_id}/read
```
{
  "tuple_key": {
      "object": "document:1"
   }
}
```

**Comment by zetaab** [comment]
@jpadilla well maybe.. but the issue is that in my integration tests I do really have like 500 documents. Each document do have 4 tuples. This means that I need to do 500 reads and then 2000 writes to api. Instead of just single sql exec command to database itself.

**Comment by aaguiarz** [comment]
Hi @zetaab 

This enhancement is captured in this Roadmap entry https://github.com/openfga/roadmap/issues/34

I'll close this issue now and we'll track it there. 

Thanks a lot for the feedback
