### ISSUE TITLE
Missing tests for `constructAuthorizationModelFromSQLRows`

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1952]
I just noticed that the last line of this function is not covered with tests 😱  is this a remainder of the unfinished auth model migration? 😬 

https://app.codecov.io/gh/openfga/openfga/blob/list-users/pkg%2Fstorage%2Fsqlcommon%2Fsqlcommon.go

<img width="1173" alt="image" src="https://github.com/user-attachments/assets/68963ac4-22ca-40a6-a676-d7da0ece79c1">

_Originally posted by @miparnisari in https://github.com/openfga/openfga/pull/1943#discussion_r1767798934_

**Comment by Madraceee** [comment]
Hey, I was going through your repository and I came across this issue. Is this still open, If so can you give me more details regarding this. I can work on this issue and try closing it.
Thanks

**Comment by Madraceee** [comment]
Cool, I will look into this

**Comment by Rizvi-Faiz** [comment]
@miparnisari  mam as no one is assigned this issue can i work on this

**Comment by aaguiarz** [comment]
@Rizvi-Faiz thanks a lot!, but I just assigned it to @Madraceee as he's been working on it already
