### ISSUE TITLE
`ResolveCheckRequest.clone()` is not thread safe

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1995]
## The problem

[`ResolveCheckRequest` struct](https://github.com/openfga/openfga/blob/2499898e616afa1c0094df1eeba33acdeca7a74c/internal/graph/resolve_check_request.go#L9) contains a field `TupleKey` that is a pointer, and a function [`clone()`](https://github.com/openfga/openfga/blob/main/internal/graph/resolve_check_request.go#L20-L42) wherein this field is not being cloned, and instead the pointer is copied. This can create race issues if two goroutines attempt to mutate a clone of a request.

## The task

1. Make `ResolveCheckRequest.clone()` thread safe. Some options:
    - creating a new TupleKey through `tuple.NewTupleKey()`, or 
    - call `proto.Clone(r.TupleKey)`, or
    - by having TupleKey NOT be a pointer
3. Update the existing unit tests: https://github.com/openfga/openfga/blob/main/internal/graph/resolve_check_request_test.go
4. Write a new unit test for `clone()` where we create a `ResolveCheckRequest` struct, and then two different goroutines call `clone()` on it.

**Comment by ovindu-a** [comment]
@miparnisari I think I can work on this if I get some more info on the issue.

**Comment by miparnisari** [comment]
@ovindu-a updated the issue with more details, let me know if it helps!

**Comment by ovindu-a** [comment]
Much more clearer to me now @miparnisari. I will work on this.

**Comment by siiddhantt** [comment]
hi @miparnisari , I opened a PR for the issue. Was working on it already
