### ISSUE TITLE
Dockerhub page missing README

### ISSUE THREAD

**Issue by rhamzeh** [openfga/openfga#207]
The dockerhub page (https://hub.docker.com/r/openfga/openfga) does not have a README because we push our own builds.

We should add pushing the README to dockerhub in our release action, e.g. using something like: https://github.com/peter-evans/dockerhub-description.

<img width="1294" alt="Screen Shot 2022-08-31 at 1 20 09 PM" src="https://user-images.githubusercontent.com/536147/187740430-c34f087a-b5ac-44a4-b835-af662a2f878c.png">

**Comment by craigpastro** [comment]
Closed via #454.

**Comment by rhamzeh** [comment]
Re-opening this as the README over on https://hub.docker.com/r/openfga/openfga is still not updated

**Comment by miparnisari** [comment]
The updating of the readme in docker is failing (https://github.com/openfga/openfga/actions/runs/4703699881/jobs/8342503094) because our Docker access token also needs the `delete` scope. See  [here](https://github.com/peter-evans/dockerhub-description/issues/70#issuecomment-1506062493)

**Comment by miparnisari** [comment]
Fixed by adding the missing scope to the Docker token
