### ISSUE TITLE
OpenFGA Docker Image 1.7.0 not reflecting updated maximum contextual tuples limit.

### ISSUE THREAD

**Issue by erlingto** [openfga/openfga#2070]
### Checklist

- [x] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [x] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [x] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [x] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [x] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

In the release notes for [OpenFGA v1.7.0](https://github.com/openfga/openfga/releases/tag/v1.7.0), the maximum number of contextual tuples was increased from 20 to 100. However, this change doesn’t appear to be applied in the Docker image for v1.7.0.

When testing with a new container, calls to /stores/{storeId}/list-objects or /stores/{storeId}/check still result in a 400 Bad Request error, with the message: "invalid ContextualTupleKeys.TupleKeys: value must contain no more than 20 item(s)".

Also, is there any plans to let developers override this limit? 

### OpenFGA version

1.7.0

### How are you running OpenFGA?

In Docker

### What datastore are you using?

In-Memory

### OpenFGA Flags

no

### Logs

   INFO    grpc_req_complete       {"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "Check", "grpc_type": "unary", "user_agent": "bruno-runtime/1.34.0", "raw_request": {"store_id":"01JBY25P4A8ASRSAZBG474ZEE6","tuple_key":null,"contextual_tuples":{"tuple_keys":[{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null},{"user":"","relation":"","object":"","condition":null}]},"authorization_model_id":"01G5JAVJ41T49E9TT3SKVS7X1J","trace":false,"context":null,"consistency":"UNSPECIFIED"}, "raw_response": {"code":"validation_error","message":"invalid ContextualTupleKeys.TupleKeys: value must contain no more than 20 item(s)"}, "query_duration_ms": "0", "peer.address": "127.0.0.1:49972", "request_id": "b2ce74cb-8995-4ffa-bbd3-ed2f3f7dc138", "store_id": "01JBY25P4A8ASRSAZBG474ZEE6", "grpc_code": 2000, "error": "rpc error: code = InvalidArgument desc = invalid CheckRequest.TupleKey: value is required; invalid CheckRequest.ContextualTuples: embedded message failed validation | caused by: invalid ContextualTupleKeys.TupleKeys: value must contain no more than 20 item(s)"}

**Comment by jpadilla** [comment]
@erlingto thanks for reporting. I can confirm the v1.7.0 release pointed to openfga/api@297cfdbbde989f5650e6bd13834875203347d3f6 as opposed to openfga/api@30477608a587fbebea8940129703c11238530f71. We're cutting a new release soon which will fix the issue.

**Comment by jpadilla** [comment]
@erlingto This should be addressed now with the https://github.com/openfga/openfga/releases/tag/v1.8.0 release.
