### ISSUE TITLE
Create config to enable cache controller

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#2148]
Also, i just noticed that `cacheControllerEnabled` has no config flags, so how will users of openfga as a binary and not library use this?

_Originally posted by @miparnisari in https://github.com/openfga/openfga/pull/2124#discussion_r1874032648_

**Comment by miparnisari** [comment]
One more thing - https://github.com/openfga/openfga/blob/9e40246c4169c649ef73207c2d5c06a36e090183/pkg/server/server.go#L440-L445

this is also never used
