### ISSUE TITLE
Read API: "type not found" is thrown when in fact the authorization model id was not found

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#250]
To reproduce:

1. Create an authorization model

```
curl --location --request POST 'http://localhost:8080/stores/01GCJB1DJ88RJ1KA5TMG5PJXQ4/authorization-models' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
    "type_definitions": [
        {
            "type": "document",
            "relations": {
                "owner": {
                    "this": {}
                }
            }
        },
        {
            "type": "group",
            "relations": {
                "member": {
                    "this": {}
                }
            }
        }
    ]
}'
```

2. Call read with an incorrect auth model id

```
curl --location --request POST 'http://localhost:8080/stores/01GCJB1DJ88RJ1KA5TMG5PJXQ4/read' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
  "tuple_key": {
    "object": "document:2021-budget",
    "relation": "owner",
    "user": "anne"
  },
  "authorization_model_id": "01GDKQT51EGCGAAAAAAAAAAAAA"
}'
````

You get this:

```
{
    "code": "type_not_found",
    "message": "Type 'document' not found"
}
```

But I expected "auth model id not found"

https://github.com/openfga/openfga/blob/7cbd9aadf38cc2c722f176c02969bd5fa6b2ee55/server/commands/read.go#L91-L94

**Comment by craigpastro** [comment]
Does it even make sense that we are validating the tuple on read? What if I want to read tuples which do not validate against the current model so I can delete them?

**Comment by miparnisari** [comment]
> Does it even make sense that we are validating the tuple on read? What if I want to read tuples which do not validate against the current model so I can delete them?

We are not validating tuples on read. We're only validating the input tuple.

**Comment by craigpastro** [comment]
> We are not validating tuples on read. We're only validating the input tuple.

I understood we are validating the input tuple on a read request. So I was wondering if we should be doing that?
