### ISSUE TITLE
register grpc request context tags middleware to inject common context

### ISSUE THREAD

**Issue by jon-whit** [openfga/openfga#282]
It'd be nice to use the [`go-grpc-middleware/tags`](https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/tags#pkg-overview) package to register a middleware that injects things like the request `store_id`, `authorization_model_id`, etc.. into the request context. Then we can use the injected tags in the request context in our logging and telemetry  throughout the app. 

Something like

```
opts := []grpc_ctxtags.Option{
        // TagBasedRequestFieldExtractor extracts the request field based on the Go struct tags of the generated protobufs

	grpc_ctxtags.WithFieldExtractor(grpc_ctxtags.TagBasedRequestFieldExtractor("store_id")),
        grpc_ctxtags.WithFieldExtractor(grpc_ctxtags.TagBasedRequestFieldExtractor("authorization_model_id")),

        // ... others
}

_ = grpc.NewServer(
	grpc.StreamInterceptor(grpc_ctxtags.StreamServerInterceptor(opts...)),
	grpc.UnaryInterceptor(grpc_ctxtags.UnaryServerInterceptor(opts...)),
)
```
and then those ctx tags will be available to us in the request context. For example

```
package logger

type ZapLogger struct {...}

var _ Logger = &ZapLogger{} // verify we implement the interface

func (l *ZapLogger) InfoWithContext(ctx context.Context, msg string, fields ...zap.Field) {
    ctxfields := zaptags.TagsToFields(ctx)
    fields = append(fields, ctxfields...)
    l.underlying.Info(msg, fields)
}
```

See these integrations for additional niceties:
https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tags/zap

**Comment by craigpastro** [comment]
From the comment in #468 it seems we won't be able to use this, so I'll close it for now.
