### ISSUE TITLE
Sporadic authorization_model_resolution_too_complex error

### ISSUE THREAD

**Issue by ghstahl** [openfga/openfga#300]
Docker on Windows
OpenFGA v.0.2.2

I have a reproducible model, [dataset](https://github.com/openfga/openfga/files/9824865/complex_error_reproducible.zip), and check that gives me the following sporadic error;
```json
{
    "code": "authorization_model_resolution_too_complex",
    "message": "Authorization Model resolution required too many rewrite rules to be resolved. Check your authorization model for infinite recursion or too much nesting"
}
```  

I make the following Check call via POSTMAN
```json
{
    "tuple_key": {
      "object": "org:f708c725-b072-4678-87d1-7fc47c52ffd3",
      "relation": "member",
      "user": "a2226717-7702-480a-a4ce-4608d0dcaea5"
    },
    "contextual_tuples": {
      "tuple_keys": [
        {
          "object": "org:f708c725-b072-4678-87d1-7fc47c52ffd3",
          "relation": "user_in_context",
          "user": "a2226717-7702-480a-a4ce-4608d0dcaea5"
        }
      ]
    } 
  }
```
or Curl
```curl
curl --location --request POST 'http://localhost:3601/stores/01GFS6AQP6WTBCHNNQR7YSA9AW/check' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
    "tuple_key": {
      "object": "org:f708c725-b072-4678-87d1-7fc47c52ffd3",
      "relation": "member",
      "user": "a2226717-7702-480a-a4ce-4608d0dcaea5"
    },
    "contextual_tuples": {
      "tuple_keys": [
        {
          "object": "org:f708c725-b072-4678-87d1-7fc47c52ffd3",
          "relation": "user_in_context",
          "user": "a2226717-7702-480a-a4ce-4608d0dcaea5"
        }
      ]
    } 
  }'
```

My Authorization Model
```
type feature
  relations
    define access as subscriber_member from associated_plan
    define associated_plan as self
    define subscriber as subscriber from associated_plan
type feature_repo
  relations
    define feature as self
type integrity
  relations
    define member as self
type org
  relations
    define admin as self and member
    define member as self and member from user_repo and user_in_context
    define plan_provider as self
    define user_in_context as self
    define user_repo as self
type permission
  relations
    define access as access from associated_feature and member from associated_permission_group
    define associated_feature as self
    define associated_permission_group as self
    define org_access as subscriber from associated_feature
type permission_group
  relations
    define member as self or admin from owner
    define owner as self
type plan
  relations
    define subscriber as self
    define subscriber_member as member from subscriber
type plan_provider
  relations
    define plan as self and plan from plan_repo and plan_in_context
    define plan_in_context as self
    define plan_repo as self
type plan_repo
  relations
    define plan as self
type user_repo
  relations
    define integrity as self
    define member as self and member from integrity

```
[complex_error_reproducible.zip](https://github.com/openfga/openfga/files/9824865/complex_error_reproducible.zip)

**Comment by rhamzeh** [comment]
Thanks for raising this issue!

**Comment by jon-whit** [comment]
👀 I think the issue may be related to the resolution context sharing resolution depth across concurrent paths of eval. Let me double check my hypothesis and get back with you. I think I may have a fix.

Good catch!

**Comment by ghstahl** [comment]
I now have a 100% reproducible case in my unit tests.  Let me know if you need that data set.

**Comment by jon-whit** [comment]
@ghstahl please share it with me if you can 👍 . I'm going to work on resolving this issue in the next few days.

**Comment by ghstahl** [comment]
## OpenFGA 
image: "openfga/openfga:v0.2.4"

## OpenFGA go sdk
github.com/openfga/go-sdk v0.1.1

## VSCODE
```
Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```
## GO
```
go version go1.19.2 windows/amd64
```
I love these types of reproducible tests.  If I run it using  ```go test ./...``` it fails every time with the complex error.  
I am hammering the openfga server with writes followed by Read(s) and Check(s)

So, I set a break point where the error occurred.  Error being the complexity response from the OpenFGA server.  

Of course, it doesn't return an error in this case. 

I speculate that the server hasn't absorbed all the information I wrote to give me a fast response at the time I am making a Check call.

**Comment by ghstahl** [comment]
New data set
This one happens every time.

[complex_error_repo_2.zip](https://github.com/openfga/openfga/files/9863308/complex_error_repo_2.zip)

**Comment by jon-whit** [comment]
@ghstahl I was taking a look at this yesterday and noticed a lot of tuples such as

```
{
    "object": "plan_repo:*",
    "relation": "plan",
    "user": "plan:*"
},
{
    "object": "plan_repo:*",
    "relation": "plan",
    "user": "plan:free"
},
```
Out of curiosity, what use case(s) do you have to use the `*` character as an object identifier (e.g. `plan_repo:*`)? We're considering making the wildcard character a reserved character and disallowing it in the object id component (`type:id`). When you write `write(plan_repo:*#plan@plan:*)` what does that mean to you and what uses does that have?

**Comment by ghstahl** [comment]
```*``` represents my global entity that represents a place where I put all my users, all known plans, etc.

***it's just a shortcut for "my_company"***

imagine a github.com user vs that same user also being a member of an org.

A user can be added to an org.
However, there is a chain up check where the user must also exist in the global ```user_repo:*```
An org can have a plan, but that plan must also be in the global ```plan_repo:*```
A plan_provider, ```plan_provider:azure_marketplace``` is assigned plans that it can sell, but those plans must also exist in the ```plan_repo:*```

My users, which are orgless, get plans and rights at a "I am just a lurker user".  


It could just be something like the following
```
{
    "object": "plan_repo:my_company",
    "relation": "plan",
    "user": "plan:*"
},
{
    "object": "plan_repo:my_company",
    "relation": "plan",
    "user": "plan:free"
},
```
A global user has access to permissions, which are carried by features, and features are carried by plans.  So I just made a ```plan:*``` and all global users get that in context of being also part of my global org.  

All users are in a ```user_repo:*```.  All users are members of ```org:*```.  My ```org:*``` is subscribed to the ``plan:*```.  

So, using contextual tuples a user acting in context of themselves (i.e. in the global org) have certain rights.

**Comment by jon-whit** [comment]
Ok, so if we were to restrict the `*` character from being an acceptable object id then you'd just have to change things to `plan_repo:my_company` instead of the shorthand `plan_repo:*`. Do I understand that correctly? If so, is that prohibitive for you in any way or does that make sense?

We're trying to avoid allowing developers to write the `*` character for an object id because it can cause confusion since it's a reserved character to mean "public access" when writing it in a 'user`' value.

**Comment by ghstahl** [comment]
I can work with that

**Comment by miparnisari** [comment]
@ghstahl I uploaded your test data to https://github.com/openfga/openfga/pull/403

**Comment by xXAvoraXx** [comment]
is there any progress? @miparnisari

**Comment by craigpastro** [comment]
👋 Unfortunately, we have no updates at the moment, but hopefully soon!

**Comment by ghstahl** [comment]
# [CANNOT REPRODUCE 0.3.2]
I changed my data set as I had stuff in there that is now not allowed.
```*``` was changed to ```global```, where I was using ```*``` to signify global (not wildcard just a single character word)
```json
{
      "object": "org:*",
      "relation": "user_repo",
      "user": "user_repo:*"
}
```
is now
```json
{
      "object": "org:global",
      "relation": "user_repo",
      "user": "user_repo:global"
}
```
* ```#members``` used to work and was changed to ```#member```.  A little strange that this one worked at all, but this one goes back to the early days.
```json
{
      "object": "permission_group:32b0ea4c91b34c2a82fb5dba6e93ee68/all",
      "relation": "member",
      "user": "org:32b0ea4c91b34c2a82fb5dba6e93ee68#members"
}
````
is now
```json
 {
      "object": "permission_group:32b0ea4c91b34c2a82fb5dba6e93ee68/all",
      "relation": "member",
      "user": "org:32b0ea4c91b34c2a82fb5dba6e93ee68#member"
}
```
[complex_error_repo_2 (2).zip](https://github.com/openfga/openfga/files/10483832/complex_error_repo_2.2.zip)

@miparnisari
[ref](https://github.com/openfga/openfga/issues/300#issue-1415670057) 
my test once the data is loaded is a check call that I could get to fail at least 40% of the time.
A successful response is.
```json
{
    "allowed": true,
    "resolution": ""
}
```
I hope that this didn't just go away without anyone knowing why.
