### ISSUE TITLE
[Bug] OpenFGA returning 500 on ListObjects

### ISSUE THREAD

**Issue by fschulte-eiwa** [openfga/openfga#314]
Hello, we are testing OpenFGA for a project and had some issues with the list_objects (normal) endpoint. Not missing data but server error.
Our tested model is as follows:

```py
type organization
  relations
    define admin as self
    define editor as self or admin
    define member as self or viewer
    define viewer as self or editor
type type_1
  relations
    define owner as self
    define editor as self or owner
    define viewer as self or editor
type type_2
  relations
    define owner as self
    define editor as self or owner or editor from parent
    define viewer as self or editor or viewer from parent
    define parent as self
```

Server setup as the documentation shows for postgres engine:

```sh
docker network create openfga
docker run -d --name postgres --network=openfga -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password postgres:14
docker run --rm --network=openfga openfga/openfga migrate --datastore-engine postgres --datastore-uri 'postgres://postgres:password@postgres:5432/postgres?sslmode=disable'
docker run --name openfga --network=openfga -p 3000:3000 -p 8080:8080 -p 8081:8081 openfga/openfga run --datastore-engine postgres --datastore-uri 'postgres://postgres:password@postgres:5432/postgres?sslmode=disable' --listObjects-max-results 50000  --listObjects-deadline 360s
```

First we added a user as admin of an organization ORG1: `{"user": "user_1","relation": "admin","object": "organization:ORG1"}`

We then performed 600 iterations of adding 25 tuples: `{"user": "type_1: UUID_1","relation": "parent","object": "type_2:UUID_n"}`
and 1 tuple giving members of ORG1 "editor" relation to each type_1 element: `{"user": "organization:ORG1#member", "relation": "editor", "object": "type_1:UUID_1"}`.

This created 600 type_1 elements and 15000 type_2 elements where each type_1 element is parent of 25 type_2 elements

When we tried listing the objects of type_2 that some user has by using the list_objects endpoint with `{"type": type_2,"relation": "editor","user": "user_1"}` we get the 15000 ids but if we try listing with a "viewer" relation rather than "editor" `{"type": type_2,"relation": "viewer","user": "user_1"}` we get a 500 response.

In the server we get the error:

```sh
2022-10-26T15:50:17.700Z        INFO    db_stats        {"method": "Check", "reads": 50, "writes": 0}
2022-10-26T15:50:17.700Z        INFO    db_stats        {"method": "Check", "reads": 38, "writes": 0}
2022-10-26T15:50:17.701Z        INFO    db_stats        {"method": "Check", "reads": 50, "writes": 0}
2022-10-26T15:50:17.702Z        INFO    db_stats        {"method": "Check", "reads": 32, "writes": 0}
2022-10-26T15:50:17.702Z        INFO    db_stats        {"method": "Check", "reads": 50, "writes": 0}
2022-10-26T15:50:17.702Z        INFO    db_stats        {"method": "Check", "reads": 29, "writes": 0}
2022-10-26T15:50:17.703Z        INFO    db_stats        {"method": "Check", "reads": 38, "writes": 0}
2022-10-26T15:50:17.710Z        INFO    db_stats        {"method": "Check", "reads": 38, "writes": 0}
2022-10-26T15:50:17.710Z        INFO    db_stats        {"method": "Check", "reads": 26, "writes": 0}
2022-10-26T15:50:17.710Z        ERROR   check_error     {"error": "postgres error: context deadline exceeded"}
github.com/openfga/openfga/pkg/logger.(*ZapLogger).ErrorWithContext
        /home/runner/work/openfga/openfga/pkg/logger/logger.go:80
github.com/openfga/openfga/server/commands.(*ListObjectsQuery).internalCheck
        /home/runner/work/openfga/openfga/server/commands/list_objects.go:233
github.com/openfga/openfga/server/commands.(*ListObjectsQuery).performChecks.func1
        /home/runner/work/openfga/openfga/server/commands/list_objects.go:207
golang.org/x/sync/errgroup.(*Group).Go.func1
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:75
2022-10-26T15:50:17.710Z        INFO    db_stats        {"method": "Check", "reads": 11, "writes": 0}
2022-10-26T15:50:17.710Z        INFO    db_stats        {"method": "Check", "reads": 11, "writes": 0}
2022-10-26T15:50:17.710Z        INFO    db_stats        {"method": "Check", "reads": 32, "writes": 0}
2022-10-26T15:50:17.710Z        ERROR   check_error     {"error": "rpc error: code = Code(4000) desc = Internal Server Error"}
github.com/openfga/openfga/pkg/logger.(*ZapLogger).ErrorWithContext
        /home/runner/work/openfga/openfga/pkg/logger/logger.go:80
github.com/openfga/openfga/server/commands.(*ListObjectsQuery).internalCheck
        /home/runner/work/openfga/openfga/server/commands/list_objects.go:233
github.com/openfga/openfga/server/commands.(*ListObjectsQuery).performChecks.func1
        /home/runner/work/openfga/openfga/server/commands/list_objects.go:207
golang.org/x/sync/errgroup.(*Group).Go.func1
```

Second step by step population of the database and listing:

- With 50 type_1 worked returning 1250 type_2 ids
- With 100 type_1 worked returning 2500 type_2 ids
- With 150 type_1 worked returning 3750 type_2 ids
- With 200 type_1 worked returning 5000 type_2 ids
- With 250 type_1 worked returning 6250 type_2 ids
- With 300 type_1 worked returning 7500 type_2 ids
- With 350 type_1 worked returning 8750 type_2 ids
- With 400 type_1 stoped working for viewer relation but for "editor" relation returned the 10000 ids.
- Then we jumped to 750 type_1 elements and the "editor" listing failed too.

**Comment by jon-whit** [comment]
@fschulte-eiwa could you please build/run the `main` branch and confirm if this has been fixed with #315?

**Comment by jon-whit** [comment]
@fschulte-eiwa awesome! These changes will go out in our next release `v0.2.5`. Keep an eye out for that release notice. It'll probably be coming soon.

**Comment by wma1729** [comment]
Do you have a date on when `v0.2.5` is coming out? I am trying to evaluate openfga and this one is a blocker.

**Comment by jon-whit** [comment]
@wma1729 we'll cut the `v0.2.5` release next Monday. Keep an eye out for the announcement.
