### ISSUE TITLE
[enhancement] A richer READ query for tuples

### ISSUE THREAD

**Issue by ghstahl** [openfga/openfga#337]
I am finding that the current Read Api is too broad in its results.
If the tuples are simple, it ok, however for more complex objects (complex by convention) it isn't ironically fined grained enough.

I have objects that look like the following.

```permission_group:{{org_id}}/blah/something/else```

Doing a Read, I can retrieve objects at the ```permission_group:``` scope.  This gives me too many results.

I would like something like a lucene query where I can do a Read that matches all objects that look like "X"
i.e. ```permission_group:{{org_id}}```   

Also, READS where I want the ```USER``` object returned should at a minimum be as good as when I READ for OBJECTs.
I would like my USER input to also be namespaced, but for now it looks like I can only have ```"user":""```
```
{
    "tuple_key": {
        "user": "permission_group:a/b",
        "relation": "associated_permission_group",
        "object":"permission_set:"
    },
    "page_size": 50
}
```
returns all permission_set(s)

vs
```
{
    "tuple_key": {
        "user": "",
        "relation": "associated_permission_group",
        "object":"permission_set:b"
    },
    "page_size": 50
}
```
Here I can only put an empty string.
Would like to be able to namespace the user.

I imagine this could explode into a bunch of opinions on how to do this, but eventually we will have to address it.

**Comment by aaguiarz** [comment]
This was added to our roadmap https://github.com/openfga/roadmap/issues/33
