### ISSUE TITLE
[Feature Request] Get all relationships a user X has on object Y

### ISSUE THREAD

**Issue by loicsikidi** [openfga/openfga#361]
Hi,

After a thorough reading of the documentation, especially [Relationship Queries](https://openfga.dev/docs/interacting/relationship-queries), it seems that it's not currently possible to answer the following question (at least) in a single request:

`What are the relationships (directs & indirects) a user X has on the object Y?`

If my affirmation is valid, it would be nice to support this feature in order to address a bunch of well-known use-cases.

For example, indicate to an application all the fined-grained permission a user has on objects at a given moment (see **capabilities** attribute on [Google Drive API](https://developers.google.com/drive/api/v3/reference/files#resource)).

I don't know if this request is hard to implement...

Thank you in advance for your answer ;)

**Comment by aaguiarz** [comment]
We added this to all of our SDKs
