### ISSUE TITLE
Using a separate Postgres schema for `openfga` tables

### ISSUE THREAD

**Issue by nokome** [openfga/openfga#393]
Hi. First, thanks for all your hard work on OpenFGA it seems like a great project and I'm excited to be trying it out.

I noticed that there does not seem to be a configuration option to specify the Postgres schema to create the `openfga` tables. Currently all the tables get created in the `public` schema:

```
mydb=# \d
                   List of relations
 Schema |          Name           |   Type   |  Owner   
--------+-------------------------+----------+----------
 public | assertion               | table    | postgres
 public | authorization_model     | table    | postgres
 public | changelog               | table    | postgres
 public | goose_db_version        | table    | postgres
 public | goose_db_version_id_seq | sequence | postgres
 public | store                   | table    | postgres
 public | tuple                   | table    | postgres
(7 rows)
```

I'd like to be able to use the same db for my application data and `openfga` data but have the latter in a separate schema. Is there a way to do this? If not are there plans to do so?

**Comment by jon-whit** [comment]
@nokome at the moment we do not support an alternative schema. There isn't any real strong reason why we've done this, and we'd be open to supporting table migrations and queries on other schemas. We'll use this issue to track progress on that work.

We're working on some other really large roadmap items right now, so I can't give you a definitive timeline for when we may get around to doing this, but the changes to support it would be relatively minor. We'll keep you updated 👍

**Comment by nokome** [comment]
@jon-whit Thanks for the response

> However, would it be just as good to add a table prefix instead of changing schemas?

I think this would be better, but I'm not sure it would be just as good as a separate schema. I don't have a lot of experience in such decisions (different schemas vs table prefixes) and haven't thought through the tradeoffs fully, but have liked the separation of concerns aspect that separate schemas has bought when used in other contexts.

I don't have a strong opinion either way and would be happy for allowing for a different prefix, particularly if that is easier to implement.

**Comment by jon-whit** [comment]
@nokome We're going to be rolling out more information in a Production Checklist eventually which will outline some deployment best practices for OpenFGA. One of the recommendations we'll include in that is to use a different database from your applications database for OpenFGA. Separating your applications database from OpenFGA's database allows the authorization workload to scale independently and avoid loading the application database. Consequently, putting the OpenFGA database under a configured schema doesn't buy you that much in that regard. If you want to skip the production best practices I could understand why you would want a table prefix, so I think it's reasonable to start with configured table prefixes.

**Comment by Tomsons** [comment]
Just saw this but its not openfga dependent but rather the underlying library used for the migrations. Just achieved it see [here](https://github.com/jackc/pgx/issues/1013)

**Comment by miparnisari** [comment]
We've documented the best practice that @jon-whit mentioned  [here](https://openfga.dev/docs/getting-started/running-in-production#database-recommendations):

> To ensure good performance for OpenFGA, it is recommended that the [database](https://openfga.dev/docs/getting-started/setup-openfga/docker#configuring-data-storage) be:
> Used exclusively for OpenFGA and not shared with other applications. This allows scaling the database independently and avoiding contention with your database.
