### ISSUE TITLE
docker image v0.2.5 logs errors occasionally

### ISSUE THREAD

**Issue by MidasLamb** [openfga/openfga#404]
I've just checked the openfga logs in our k8s cluster, and I noticed the following error being logged quite a few times:
```
2022-12-13T12:33:26.532Z	ERROR	check_error	{"error": "rpc error: code = Code(4000) desc = Internal Server Error"}
github.com/openfga/openfga/pkg/logger.(*ZapLogger).ErrorWithContext
	/home/runner/work/openfga/openfga/pkg/logger/logger.go:75
github.com/openfga/openfga/server/commands.(*ListObjectsQuery).internalCheck
	/home/runner/work/openfga/openfga/server/commands/list_objects.go:309
github.com/openfga/openfga/server/commands.(*ListObjectsQuery).performChecks.func1
	/home/runner/work/openfga/openfga/server/commands/list_objects.go:277
golang.org/x/sync/errgroup.(*Group).Go.func1
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75
```

I'm not entirely sure why, because functionally everything seems fine as far as we can tell.
Making this issue more in a "heads-up" kind of way.

**Comment by jon-whit** [comment]
@MidasLamb thanks for the report. The @openfga/core team actually has a meeting scheduled today to go over the logging in OpenFGA and improve logs and metadata included in them etc.. We'll review this as part of that process and get back with you 👍

**Comment by miparnisari** [comment]
Hey @MidasLamb, that error is being logged from within ListObjects' internal call to Check. One possibility is that the `listObjects-deadline` setting is set too low and Check is being cancelled internally.

**Comment by miparnisari** [comment]
@MidasLamb i'm glad that resolved it :) In regards to the missing entries from the result, ListObjects performs Checks against all objects of the type that you specified, so it's possible that it was running out of time to check all of them.

**Comment by MidasLamb** [comment]
We've just bumped our service using OpenFGA from our test environment to our staging, and suddenly the API calls making use of OpenFGA are taking WAY longer, it used to be ~5 seconds and on staging it suddenly jumped to at least 30 seconds, sometimes even more. I've done some optimizations on staging to get it down to ~15-20 seconds. I don't immediately find any reason why there would be a jump like this.
I've also noticed that if there are some OpenFGA checks aftereach other, they progressively seem to get longer (this is purely a thought, haven't had time to properly check this), but it seems that there is some bottleneck in the check call

**Comment by MidasLamb** [comment]
I'm just dumping information here for now, we're close to releasing our big authN & authZ refactor which is supported by OpenFGA, so I'm currently in the "What's the fastest way to fix this"-mode rather than "Let's get to the bottom of this"-mode. After the refactor is released I can help dig down deeper and potentially provide some insights from our production environment

**Comment by aaguiarz** [comment]
Hi @MidasLamb could you please email me to andres.aguiar@okta.com? We can hop on a call if that's good OK with you

**Comment by aaguiarz** [comment]
- Can you expand on which API calls are taking 5 seconds and now 30 seconds? Those response times look way high.
- How many tuples to you have in each environment?
- Are the authorization models the same?
- Are you defining indexes on your MySQL schema?

**Comment by MidasLamb** [comment]
@aaguiarz , the API calls are ListObject calls.
For the 5s environment I have the 988 tuples, for the 30s environment I have 4335.
Authorization model is the exact same for both environments.
The indexes are the ones created by the migration, so a primary index on:
* store
* object_type
* object_id
* relation
* _user
And a reverse lookup on
* store
* object_type
* relation
* _user

**Comment by aaguiarz** [comment]
Hi @MidasLamb 

That behavior is expected, as the current ListObject performance increases significantly with the number of tuples. 

We have a new ListObjects implementation almost ready that will address those issues, but it's currently disabled. We'll release a new version later today that will let you enable it through configuration. The new implementation has a few edge cases that are not working well:

- Support for public access (tuples with user = "*")
- Models that define intersection and exclusion (use `and` or `but not`)

If you have any of those scenarios, then ListObjects might return incorrect results.

Additionally, the ListObjects optimizations rely on the [DSL schema 1.1. changes](https://openfga.dev/docs/modeling/migrating/migrating-schema-1-1), so you'd need to update your model to that version to take advantage of it.

Please let us know if this helps.

**Comment by MidasLamb** [comment]
I've now worked around it by querying the underlying data storage directly, once released I'll check how it compares!
The restrictions don't matter for us at the moment so for that part an improvement would be great!

**Comment by rhamzeh** [comment]
Hey @MidasLamb! The team has pushed out a new `v0.3.1` release with support for enabling the experimental optimized `ListObjects` functionality.

It requires a model in the v1.1 schema, and does not have complete support for `and`, `but not` and Type-bound Public Access (`*` and `type:*`).

If you do get a chance to try it out, let us know what you think!
