### ISSUE TITLE
`v0.3.0`: Write validation is being performed on assertions

### ISSUE THREAD

**Issue by rhamzeh** [openfga/openfga#411]
### Affected Version
`v0.3.0`

### Model Used
```py
model
  schema 1.1
type user
type doc
  relations
    define owner: [user]
    define can_share: owner
```

### Steps To Reproduce
```sh
curl -X PUT 'http://127.0.0.1:8080/stores/01GM9JTY114HWA8XRCDG46K3PY/assertions/01GM9R4RGBPQC66CGPYA499G93' \
  -H 'Content-Type: application/json' \
  -d '{"assertions":[{"tuple_key":{"user":"user:henry","relation":"can_share","object":"doc:roadmap"},"expectation":true}]}'
```

### Response Expected
204 No Content

### Response Received
400 Bad Request
```json
{
  "code": "validation_error",
  "message": "Invalid tuple 'doc:roadmap#can_share@user:henry'. Reason: type 'user' is not an allowed type restriction for 'doc#can_share'"
}

```

Reported by [kdubb on Discord](https://discord.com/channels/759188666072825867/1052745870786973726)

**Comment by kdubb** [comment]
Just to be clear, I encountered this issue with `0.3.0`.

**Comment by adriantam** [comment]
@kdubb , the issue is now fixed and should be available in the latest "main" branch.  It will be available in the next release.
