### ISSUE TITLE
Configuration property: maxTuplesPerWrite does not work

### ISSUE THREAD

**Issue by psadovsky** [openfga/openfga#421]
The default value according to this file https://github.com/openfga/openfga/blob/main/.config-schema.json is **100**. When I try to write more than 25 tuples within Postgres as storage, then I get:

`
{
    "code": "tuple_keys_too_many_or_too_few_items",
    "message": "invalid TupleKeys.TupleKeys: value must contain between 1 and 25 items, inclusive"
}
`

**Comment by rhamzeh** [comment]
Thanks for reporting @psadovsky - we'll take a look

**Comment by rhamzeh** [comment]
Related fix: https://github.com/openfga/api/pull/65

**Comment by craigpastro** [comment]
Hi @psadovsky 👋  Thank you for the report 🙌 

A fix has now been merged into main. We hope to cut a new release that includes the fix sometime soon. Please let us know if it fixes the problem.

**Comment by rhamzeh** [comment]
Hey @psadovsky - thanks to @craigpastro and the team, the fix for this is now out in [OpenFGA `v0.3.1`](https://github.com/orgs/openfga/discussions/91).

Please let us know if you get a chance to try it out.

**Comment by psadovsky** [comment]
Hello everyone, it works now. Thank you.
