### ISSUE TITLE
[Question] Production openfga/openfga Image Configuration

### ISSUE THREAD

**Issue by jayoungers** [openfga/openfga#436]
I'm looking to get this up and running in a production grade environment, and ran into the following questions (these are in reference to the standard docker image such as `openfga/openfga:v0.3.1`):

1. Is there a way to adjust the server's base path?  I'd like to avoid using a proxy, and let the load balancer forward requests via a prefix: as of now I can simply set that as `/stores`, but I'm guessing it would be better to be able to set a true base path (e.g. `/api/auth` or something along those lines)
2. Is there a way to run a cli command against the `/healthz` endpoint as an in-container health check?  Or would the image need to be altered to install something like curl?
3. For the Postgres provider, is it possible to specify connections for a write instance vs a read replica?

I couldn't find related configurations in https://github.com/openfga/openfga/blob/main/.config-schema.json

**Comment by jon-whit** [comment]
> Is there a way to adjust the server's base path? I'd like to avoid using a proxy, and let the load balancer forward requests via a prefix: as of now I can simply set that as /stores, but I'm guessing it would be better to be able to set a true base path (e.g. /api/auth or something along those lines)

I'm curious what the reasoning behind this is? If you need to map alternative endpoints to the endpoints served by OpenFGA then you will have to have a reverse proxy of some fashion.

An alternative to this would be that you could integrate OpenFGA as a library in your own Go app and serve the RPC endpoints on whatever HTTP endpoints you'd like, but I wouldn't advise that as it would create an inconsistent and non-standard OpenFGA integration that would not necessarily be drop in compatible with future OpenFGA tooling and integrations.

> Is there a way to run a cli command against the /healthz endpoint as an in-container health check? Or would the image need to be altered to install something like curl?

There is not currently a CLI target to check Health, but you can use `curl`. For example
```
docker run -d --rm --name openfga -p 8080:8080 openfga/openfga run
curl -X GET http://localhost:8080/healthz

```

> For the Postgres provider, is it possible to specify connections for a write instance vs a read replica?

OpenFGA has endpoints to write and read/query data from the underlying persistence engine. For this reason any connection to the underlying database needs to support writes and reads. We haven't engineered OpenFGA specific to an underlying cloud vendor that may or may not support streaming replication, read replicas, etc..

**Comment by jayoungers** [comment]
> I'm curious what the reasoning behind this is? If you need to map alternative endpoints to the endpoints served by OpenFGA then you will have to have a reverse proxy of some fashion.

If our load balancer was configured as:
```
/serviceA* -> serviceA containers
/serviceB* -> serviceB containers
/openfga* -> openfga containers
```

The serviceA and serviceB applications would be fully aware they're receiving all requests as `/serviceA/entities/...`, but for openfga I don't believe there's a way to let it know `/openfga/stores/...` is where requests will be coming opposed to `/stores/...`

If this type of functionality isn't supported by the app or by the SDKs, falling back to using the domain shouldn't be an issue.

> > For the Postgres provider, is it possible to specify connections for a write instance vs a read replica?
> 
> OpenFGA has endpoints to write and read/query data from the underlying persistence engine. For this reason any connection to the underlying database needs to support writes and reads. We haven't engineered OpenFGA specific to an underlying cloud vendor that may or may not support streaming replication, read replicas, etc..

This might be something to keep in mind as a future enhancement: for the primarily read oriented endpoints, allowing them to use a separate connection string (falling back to the standard)

**Comment by jon-whit** [comment]
@jayoungers 

> The serviceA and serviceB applications would be fully aware they're receiving all requests as `/serviceA/entities/...`, but for openfga I don't believe there's a way to let it know `/openfga/stores/...` is where requests will be coming opposed to `/stores/...`

It's quite common for LBs to have path rewrite rules. I know that certain AWS and GCP LBs support path rewrite rules, and if you're behind a reverse proxy most reverse proxies support path stripping before proxying the request. Anyhow, we'll keep it in mind. In the meantime I recommend using path rewrite rules in your LB configurations.

> This might be something to keep in mind as a future enhancement: for the primarily read oriented endpoints, allowing them to use a separate connection string (falling back to the standard)

We'll keep it in mind, though we have to be careful not to leak our storage interface design to any specific connection protocol(s), and hence I'm not super fond of the idea at this time. Not all databases that we may want to support separate write and read connection endpoints, and so introducing something like this would start to leak the storage engine design.

**Comment by jon-whit** [comment]
@jayoungers you ok if I close this for now? We can cross-link if we end up supporting an alternative base-path in the future.

**Comment by jayoungers** [comment]
> @jayoungers you ok if I close this for now? We can cross-link if we end up supporting an alternative base-path in the future.

Yep! Sorry; I'll close this.  

Just a heads up regarding the prior comment, as far as AWS is concerned I don't believe ALBs or NLBs are capable of altering requests (rewriting paths); you can respond with a redirection result containing a different path, but functionality to forward an altered requested to a target I don't believe exists.
