### ISSUE TITLE
feat: add a `migrate` target command to run database schema migrations

### ISSUE THREAD

**Issue by jon-whit** [openfga/openfga#44]
It would be nice if we added a `migrate` command to our CLI that runs database schema migrations so that developers can migrate up to the latest schema for a given release of OpenFGA.

```
Run database schema migrations needed for the OpenFGA server.

The migrate command is used to migrate up to a specific revision of the database schema needed for OpenFGA. If
the revision is omitted the latest or "HEAD" revision of the schema will be used.

Usage:
openfga migrate [revision]

Flags:
    --datastore-engine string - the type of database engine to run the migrations for (postgres, mysql, cockroachdb, etc..)
    --datastore-uri string        - the database connection uri (driver included) of the database to run the migrations against
```

Examples:
- `openfga migrate --datastore-engine postgres --datastore-uri postgres://localhost:5432` - migrates up to the latest "HEAD" revision of the database schema for postgres

- `openfga migrate --datastore-engine mysql --datastore-uri mysql://localhost:3306 1` - migrates up to the first revision of the database schema for mysql

I recommend we look into the https://github.com/golang-migrate/migrate package to simplify the migration execution process for a variety of database engines.

**Comment by matthewpereira** [comment]
This looks good to me. Thanks for writing it up!

**Comment by vavsab** [comment]
@craigpastro when are you going to create a release for it?

**Comment by craigpastro** [comment]
👋 @vavsab. Sorry for the delay. Need to merge the docs on it https://github.com/openfga/openfga.dev/pull/175, and we will work on pushing it out a new release after that. Thanks!
