### ISSUE TITLE
HTTP status 400 when relation not found

### ISSUE THREAD

**Issue by psadovsky** [openfga/openfga#442]
First of all, there has been changed error "relation_not_found" to "validation_error", I am not sure if this concept is correct because "relation_not_found" makes more sense than "validation_error". The "validation_error" seems more general and it can encapsulate much more errors.

**Comment by mightysood** [comment]
Hi @rhamzeh , Can I work on this?

**Comment by rhamzeh** [comment]
Thanks for stepping up @mightysood!

This might need a bit of sync as the team are still considering overhauling our error responses.

Will check-in with the team to make sure this is straightforward so that you don't waste effort on it and get back to you

**Comment by mightysood** [comment]
`{"code":"validation_error","message":"relation 'document#reader1' not found"}`

We are sending an appropriate message with the validation_error code.

**Comment by miparnisari** [comment]
@psadovsky can you share in what API you saw that error? If you saw it in the Check API, I think the current error makes sense because the `relation` must have been a part of the input.

**Comment by psadovsky** [comment]
@miparnisari I saw it in the Check API. I am not sure, what you think about that `relation` must be part of the input. The error comes out when I send a valid check request, but the `relation` in this check request is not in the authorization model.

**Comment by jon-whit** [comment]
Seems to work as expected. If you write a model and attempt to write a tuple that references a bad relation you get an HTTP 400. If you attempt to make a Check that references an undefined relation on the type in the model then you get HTTP 400. Those are appropriate validation error codes for this behavior.

https://github.com/openfga/openfga/assets/2899204/9f2fcc56-97c3-4738-9eb0-f9b640c296af
