### ISSUE TITLE
mysql: migrations fail to apply when sql_mode set to NO_ZERO_IN_DATE

### ISSUE THREAD

**Issue by easyCZ** [openfga/openfga#449]
With a MySQL database, which has the `sql_mode`[[ref](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date)] set to `NO_ZERO_IN_DATE` the migrations will fail because they do not specify a default value for TIMESTAMP.

```
2023/01/06 20:13:24 ERROR 001_initialize_schema.sql: failed to run SQL migration: failed to execute SQL query "CREATE TABLE store (\n\tid CHAR(26) PRIMARY KEY,\n    name VARCHAR(64) NOT NULL,\n\tcreated_at TIMESTAMP NOT NULL,\n\tupdated_at TIMESTAMP,\n\tdeleted_at TIMESTAMP\n);\n": Error 1067 (42000): Invalid default value for 'updated_at'
```

I believe a possible fix for this is to set the TIMESTAMP fields with a default value, which could be Unix 0 timestamp.

**Comment by easyCZ** [comment]
I can confirm that setting the `updated_at TIMESTAMP DEFAULT '1970-01-01 00:00:01'` fixes the issue. The remaining question is whether there's an application level change that also needs to be made to treat this value as a zero value.

Example change https://github.com/easyCZ/openfga/commit/36ca52b1b4486e398c51d331481ca47a27366868

**Comment by easyCZ** [comment]
Thanks for the reply @jon-whit. 

While it is deprecated, [it is still present in the current latest MySQL version 8](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_in_date). As such, it feels it support for it should be in scope.

For my use-case, I cannot introduce a new database instance just for OpenFGA, and that means I can only use an existing MySQL instance which happens to have the STRICT mode enabled globally.

Without this change, my only course of action would be to fork OpenFGA and make the change in the fork as without it, I cannot proceed to evaluate OpenFGA viability.

**Comment by easyCZ** [comment]
Thanks. Happy to contribute the changes as well, assuming you can provide guidance on how you'd like the defaults to behave.

One way to handle this case would be a DateTime with specific serialization per datastore type. Similar to how Gorm handles types differently based on the backend db. This would then allow us to hide the fact that a particular value (like Unix 0) should be treated as `null`

**Comment by jon-whit** [comment]
> Thanks. Happy to contribute the changes as well, assuming you can provide guidance on how you'd like the defaults to behave.
> 
> One way to handle this case would be a DateTime with specific serialization per datastore type. Similar to how Gorm handles types differently based on the backend db. This would then allow us to hide the fact that a particular value (like Unix 0) should be treated as `null`

Awesome! We'd love the contribution.

Let's work on treating the zero value for `time.Time` as nullable/nil so that API responses such as the response for the [`ListStores API`](https://openfga.dev/api/service#/Stores/ListStores) omits the `updated_at` or `deleted_at` fields if it is nil or the zero value. If you could do that for the currently supported storage engines that would be great 👍

**Comment by miparnisari** [comment]
Closing in favor of https://github.com/openfga/openfga/issues/1399
