### ISSUE TITLE
[Bug] OpenFGA<>Postgres: too many clients already

### ISSUE THREAD

**Issue by xXAvoraXx** [openfga/openfga#464]
Hello, what exactly means that error -> 

OpenFGA version v0.3.2

**POSTGRES LOG**
```
2023-01-19 10:59:22.563 UTC [4713] FATAL:  sorry, too many clients already
2023-01-19 10:59:22.565 UTC [4704] FATAL:  sorry, too many clients already
2023-01-19 10:59:22.567 UTC [4712] FATAL:  sorry, too many clients already
2023-01-19 10:59:22.569 UTC [4706] FATAL:  sorry, too many clients already
2023-01-19 10:59:22.573 UTC [4710] FATAL:  sorry, too many clients already
2023-01-19 10:59:25.440 UTC [4864] LOG:  could not receive data from client: Connection reset by peer
```

**OPENFGA LOG**

`[31mERROR[0m    check_error    {"error": "postgres error: failed to connect to database=postgres: server error (FATAL: sorry, too many clients already (SQLSTATE 53300))"}`

```
2023-01-19T10:59:25.431Z    [31mERROR[0m    check_error    {"error": "sql error: failed to connect to `host=postgres user=postgres database=postgres`: server error (FATAL: sorry, too many clients already (SQLSTATE 53300))"}
github.com/openfga/openfga/pkg/logger.(*ZapLogger).ErrorWithContext
    /home/runner/work/openfga/openfga/pkg/logger/logger.go:77
github.com/openfga/openfga/server/commands.(*ListObjectsQuery).internalCheck
    /home/runner/work/openfga/openfga/server/commands/list_objects.go:330
github.com/openfga/openfga/server/commands.(*ListObjectsQuery).performChecks.func2
    /home/runner/work/openfga/openfga/server/commands/list_objects.go:304
golang.org/x/sync/errgroup.(*Group).Go.func1
    /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75
2023-01-19T10:59:25.431Z    [31mERROR[0m    check_error    {"error": "rpc error: code = Code(4000) desc = Internal Server Error"}
github.com/openfga/openfga/pkg/logger.(*ZapLogger).ErrorWithContext
    /home/runner/work/openfga/openfga/pkg/logger/logger.go:77
github.com/openfga/openfga/server/commands.(*ListObjectsQuery).internalCheck
    /home/runner/work/openfga/openfga/server/commands/list_objects.go:330
github.com/openfga/openfga/server/commands.(*ListObjectsQuery).performChecks.func2
    /home/runner/work/openfga/openfga/server/commands/list_objects.go:304
golang.org/x/sync/errgroup.(*Group).Go.func1
    /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75
2023-01-19T10:59:25.432Z    [34mINFO[0m    grpc_complete    {"method": "/openfga.v1.OpenFGAService/ListObjects", "took": 7.96722148}
```

**OPENFGA INITIAL START LOG**
```
2023-01-19T10:58:15.019Z    [34mINFO[0m    🧪 experimental features enabled: [list-objects-optimized]
2023-01-19T10:58:15.041Z    [34mINFO[0m    using 'postgres' storage engine
2023-01-19T10:58:15.041Z    [34mINFO[0m    using 'preshared' authentication
2023-01-19T10:58:15.041Z    [33mWARN[0m    grpc TLS is disabled, serving connections using insecure plaintext
2023-01-19T10:58:15.041Z    [34mINFO[0m    🚀 starting openfga service...    {"version": "v0.3.2", "date": "2023-01-18T23:22:31Z", "commit": "84fc17ace670e9f9c62592f6e6310ba6b8b758d0", "go-version": "go1.18.9"}
2023-01-19T10:58:15.043Z    [34mINFO[0m    grpc server listening on '0.0.0.0:8081'...
2023-01-19T10:58:15.045Z    [34mINFO[0m    HTTP server listening on '0.0.0.0:8080'...
```

**DOCKER ENV**
```
OPENFGA_RESOLVENODELIMIT 38
OPENFGA_LISTOBJECTSDEADLINE 100s
OPENFGA_HTTP_UPSTREAMTIMEOUT 110s
OPENFGA_EXPERIMENTALS list-objects-optimized
```

I got that erorr While I call the list-objects end point

this is my tuples->

```
{
    "authorization_model_id": "01GQ231DEQHA6448WVBF753QEB",
    "type": "permission_access",
    "relation": "can_access",
    "user": "user:d1ce1fdd-c013-44cb-b4c8-d5088b70bfd2",
    "contextual_tuples": {
        "tuple_keys": [
            {
                "user": "user:d1ce1fdd-c013-44cb-b4c8-d5088b70bfd2",
                "relation": "member_in_context",
                "object": "integrity:52d0a3e1-195d-43c6-ab1f-114f7ea91edc"
            },
            {
                "user": "user:d1ce1fdd-c013-44cb-b4c8-d5088b70bfd2",
                "relation": "user_in_context",
                "object": "business:6a7ffbcb-2296-49ac-80da-b0e237a5c5a1"
            }
        ]
    }
}
```

**AUTHORIZATION MODEL**

```
type permission
  relations
    define associated_feature: [feature]
    define feature_access: feature_member from associated_feature
    define feature_owner_access: feature_owner_member from associated_feature
    define subscriber_business: subscriber_business from associated_feature
    
type permission_repo
  relations
    define associated_permission: [permission] 
    
type permission_access
  relations
    define associated_permission: [permission]
    define blocked: [user]
    define access: [user] but not blocked
    
    define permission_access: feature_access from associated_permission but not blocked
    define can_owner_access: feature_owner_access from associated_permission but not blocked
    
    define associated_business_role: [business_role#business_role_member] but not blocked    
    define can_access_individual_or_role: access or associated_business_role
    
    define can_access_member: permission_access and can_access_individual_or_role
    
    define can_access: can_access_member or can_owner_access
    
    define subscriber_business: subscriber_business from associated_permission
```

I reported the bug on Discord and added it on github.

**Comment by craigpastro** [comment]
The non-optimized version of list objects uses concurrent checks underneath the hood so depending on how many tuples you have in the system this could send a lot of requests to Postgres, which then could exceed Postgres' max connections. Maybe you can try increasing the max_connections on Postgres, or perhaps decreasing max-open-conns in OpenFGA? The latter at the cost of latency I suppose. There is also an optimized version of list objects, but at the moment it doesn't work with models that include exclusion or intersection.

**Comment by xXAvoraXx** [comment]
> The non-optimized version of list objects uses concurrent checks underneath the hood so depending on how many tuples you have in the system this could send a lot of requests to Postgres, which then could exceed Postgres' max connections. Maybe you can try increasing the max_connections on Postgres, or perhaps decreasing max-open-conns in OpenFGA? The latter at the cost of latency I suppose. There is also an optimized version of list objects, but at the moment it doesn't work with models that include exclusion or intersection.

I'm trying to get all the permissions that the user has access to. For example, a user can access 65 types of permissions. By using these permissions, I plan to turn the user's access to the pages on the screen on the frontend side. So I need all permissions after my user login. Before I became OpenFGA, I was putting all these permissions inside the jwt token.

I'm using 'and' and 'but not' syntaxes, when will there be an optimization for this?

**Comment by xXAvoraXx** [comment]
After adding this to the env 'OPENFGA_DATASTORE_MAXOPENCONNS 2' I don't know how it happened but the query that used to take 11 seconds now takes 800ms. and it worked.

**Comment by craigpastro** [comment]
> I'm using 'and' and 'but not' syntaxes, when will there be an optimization for this?

Hopefully soon, but we can't make any promises. It is on the roadmap and people are certainly asking for it.

> After adding this to the env 'OPENFGA_DATASTORE_MAXOPENCONNS 2' I don't know how it happened but the query that used to take 11 seconds now takes 800ms. and it worked.

😳 That's certainly surprising! Nothing else changed?

**Comment by xXAvoraXx** [comment]
> > I'm using 'and' and 'but not' syntaxes, when will there be an optimization for this?
> 
> Hopefully soon, but we can't make any promises. It is on the roadmap and people are certainly asking for it.
> 
> > After adding this to the env 'OPENFGA_DATASTORE_MAXOPENCONNS 2' I don't know how it happened but the query that used to take 11 seconds now takes 800ms. and it worked.
> 
> 😳 That's certainly surprising! Nothing else changed?

before adding this 'OPENFGA_DATASTORE_MAXOPENCONNS 2' environment variable, the result of the request was incomplete and took a long time. But after adding it, it started working without any errors.

**Comment by craigpastro** [comment]
Hi @xXAvoraXx 👋  I'll close this issue for now. If you are still experiencing problems please reopen it. Thanks!

ps. A fix for https://github.com/openfga/openfga/issues/380 was merged to `main` which may also improve performance. Please take a look!
