### ISSUE TITLE
Provide a method to parse DSL

### ISSUE THREAD

**Issue by kian99** [openfga/openfga#509]
Hi,

I'm wondering how other people store their authorisation model. We are writing the auth model with the DSL syntax (usually on the playground), copying the JSON and storing this in source control.

I would prefer to store the DSL directly in source control and then parse this during initilisation. Would it be possible to expose a method on the client or even the server to parse the DSL into JSON?

**Comment by rhamzeh** [comment]
Hi @kian99

We are considering whether we allow the sever to parse the DSL, but at the moment it only accepts json.

You can still store your files in the DSL format and use https://github.com/openfga/syntax-transformer to generate the json from them.

We are working on better tooling to improve this even further (such as with an official CLI, and better CI/CD integration), and we'd love to take any suggestions you might have into consideration, so let us know if you have any particular use cases you'd like us to tackle.

**Comment by kian99** [comment]
The syntax transformer is exactly what I was looking for, thanks!

I will point some colleagues towards this thread if there are any suggestions but I'll close the ticket for now as my questions have been answered.
