### ISSUE TITLE
Internal error for check in certain model with schema 1.0 

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#531]
For the following model

```
type rule
  relations
    define assigned as self
    define has_assigned as u1 from assigned or u2 from assigned
type parent1
  relations
    define role as self
    define u1 as role
type parent2
  relations
    define role as self
    define u2 as role
type user
```

the following check will result in internal error
```

{
    "tuple_key": {
        "object": "rule:X",
        "relation": "has_assigned",
        "user": "user:1"
    },
    "contextual_tuples": {
        "tuple_keys": [
            {
                "user":"user:1",
                "relation": "role",
                "object": "parent2:a"
            },
            {
                "user": "parent2:a",
                "relation": "assigned",
                "object": "rule:X"
            }
        ]
    }
}

```

Note that we cannot reproduce the issue in schema 1.1 as the following model is invalid due to type restriction validation

```
model
  schema 1.1
type rule
  relations
    define assigned: [parent1, parent2]
    define has_assigned: u1 from assigned or u2 from assigned
type parent1
  relations
    define role: [user]
    define u1: role
type parent2
  relations
    define role: [user]
    define u2: role
type user

```

**Comment by jon-whit** [comment]
@adriantam why is the 1.1 model variation that you posted above invalid? That looks like a valid model.

**Comment by adriantam** [comment]
> @adriantam why is the 1.1 model variation that you posted above invalid? That looks like a valid model.

`u1` is not a valid relation for `parent2` and `u2` is not a valid relation for `parent1`

**Comment by adriantam** [comment]
> > > @adriantam why is the 1.1 model variation that you posted above invalid? That looks like a valid model.
> > 
> > 
> > `u1` is not a valid relation for `parent2` and `u2` is not a valid relation for `parent1`
> 
> And why is that an issue? If _at least_ one of the computed relations on a tupleset relationship is defined for the type definition, then it should be treated as a valid definition should it not? In this case, the second example you gave (the 1.1 model) that actually should be subject to the same bug you're reporting herein for 1.0 models. I'd argue that you gave two good examples for both 1.0 and 1.1 that we should make sure behave as expected.
> 
> I don't personally see anything wrong with that model..

As discussed offline, added https://github.com/openfga/syntax-transformer/issues/113 to update the behaviour on the transformer side.
