### ISSUE TITLE
parallelize tests

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#581]
https://github.com/openfga/openfga/blob/fcfad88703d51f3e573511f4b92ea6a31d61febb/tests/check/check.go#L80

These tests should be parallelized. Also these:

https://github.com/openfga/openfga/blob/fcfad88703d51f3e573511f4b92ea6a31d61febb/tests/check/check_test.go#L25-L33

**Comment by adriantam** [comment]
We probably also want to do this for ListObject tests too
