### ISSUE TITLE
Bug: Computed userset not evaluated properly for listobject

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#602]
For the following model
```
model
  schema 1.1
type folder
  relations
    define can_view: viewer
    define parent: [folder]
    define viewer: [user] or viewer from parent
type user
```

With the following tuples
```
folder:a#viewer@user:anne
folder:b#parent@folder:a
```

The call `ListObjects( type: folder, relation: can_view, user: user:anne )` returns only `[folder:a]`

We expect `[folder:a,folder:b]`

Note that this is isolated to be in the reverseExpand implementation as 
```
model
  schema 1.1
type folder
  relations
    define banned: [user]
    define can_view: viewer but not banned
    define parent: [folder]
    define viewer: [user] or viewer from parent
type user
``` 
produces the correct result.

Note that the the call `ListObjects( type: folder, relation: viewer, user: user:anne )` returns `[folder:a, folder:b]` as expected

**Comment by miparnisari** [comment]
I suspect this bit: https://github.com/openfga/openfga/blob/ebf3a0f8597e3bbb13de072e6e78652a4f28b952/internal/graph/graph.go#L185-L233
