### ISSUE TITLE
Extends 'from' statement in authorization model

### ISSUE THREAD

**Issue by geoffroybraun** [openfga/openfga#642]
Hi,

some use cases I have to address in real-world scenarios require the `from` statement to be extended. Let say I have to following use case in Gherkin :

```gherkin
Given an existing user Test
And user Test is owner of a car SUV
And user Test is member of family Fga
And an existing user Other
When user Other becomes member of family Fga
Then user Other is driver of car SUV
```

Actually, this simple scenario would require the following authorization model, if I'm not mistaking it:

```
model
  schema 1.1
type user
type car
  relations
    define owner: [user]
    define driver: owner or [family#member]
type family
  relations
    define member: [user]
```

Also, I would have to insert the following tuples:
| User | Relation | Object |
|------|---------|-------|
| user:Test | owner | car:SUV |
| user:Test | member | family:Fga |
| user:Other | member | family:Fga |
| family:Fga#member | driver | car:SUV |

The purpose of this suggestion is to allow to use relations from another object's relations with a statement such as `[family#member] from owner`. With such an evolution, I would be allowed to have to the previous use case work with the following authorization model:

```
model
  schema 1.1
type user
type car
  relations
    define owner: [user]
    define driver: owner or [family#member] from owner
type family
  relations
    define member: [user]
```

And finally, I would only have to insert the following tuples:
| User | Relation | Object |
|------|---------|-------|
| user:Test | owner | car:SUV |
| user:Test | member | family:Fga |
| user:Other | member | family:Fga |

Please let me know if this evolution is realistic, or if you need further comments / explanations about it. Thanks!

**Comment by rhamzeh** [comment]
Hey @geoffroybraun - The way to do what you are asking is:
```py
model
  schema 1.1
type user
type car
  relations
    define owner: [user]
    define driver: owner or member from owner
type family
  relations
    define member: [user]
```

**Comment by rhamzeh** [comment]
> unfortunatly, it does not seem to work...

Sorry that was a very hasty distracted reply from my end - it definitely won't work, as the owner isn't the family!

For your case, what we would suggest, is making use of biderectional writes to do this - that means writing tuples to indicate that a user is a member of the family, and writing tuples to indicate that the family is related to the user.

For example:

Model:
```py
model
  schema 1.1
type user
  relations
    define family: [family]
    define family_member: member from family
type car
  relations
    define owner: [user]
    define driver: owner or family_member from owner
type family
  relations
    define member: [user]
```

Tuples:
```json
[
  {
    "user": "user:Test",
    "relation": "owner",
    "object": "car:SUV"
  }, {
    "user": "user:Test",
    "relation": "member",
    "object": "family:Fga"
  }, {
    "user": "family:Fga",
    "relation": "family",
    "object": "user:Test"
  }, {
    "user": "user:Other",
    "relation": "member",
    "object": "family:Fga"
  }, {
    "user": "family:Fga",
    "relation": "family",
    "object": "user:Other"
  }
]
```


https://play.fga.dev/stores/create/?id=01GW5Y8A25D0PWJNYRNC2X5KTE

**Comment by rhamzeh** [comment]
@XVincentX, you are right. You do have a similar use-case.

What do you think about something like the model below?

Model
```py
model
  schema 1.1
type group
  relations
    define member: [employee]
    define sibling: [group]
    define sibling_member: member from sibling
type employee
  relations
    define group: [group]
    define view_employmentInfo: [group] or sibling_member from group
```

Tuples
```json
[
  {
    "user": "group:engineering",
    "relation": "group",
    "object": "employee:bob"
  }, 
  {
    "user": "employee:bob",
    "relation": "member",
    "object": "group:engineering"
  }, {
    "user": "group:hr-engineering",
    "relation": "sibling",
    "object": "group:engineering"
  }, {
    "user": "group:engineering",
    "relation": "sibling",
    "object": "group:hr-engineering"
  }, {
    "user": "group:hr-engineering",
    "relation": "group",
    "object": "employee:frank"
  }, {
    "user": "employee:frank",
    "relation": "member",
    "object": "group:hr-engineering"
  }
]
```

https://play.fga.dev/stores/create/?id=01GW5YV3T476SSGD6V9WJVB05T

**Comment by geoffroybraun** [comment]
Hi @rhamzeh !

Once again, thank you for the reply. The idea of the suggested syntax is to avoid having everything in the `user` type. The solution you suggested seems to be good, as it is working and we tested that approach before coming to you with this issue, but on a company scale, expecially a large one, I can't imagine how many relations the `user` could have, making it very confusing and hard to maintain over time...

The idea of the syntax `[type#relation] from other_type` intends to avoid having to "pollute" the `user` type, which will be at the very beginning of every question asked to OpenFGA.

Let me know if you need further explanation for that, thanks!

**Comment by aaguiarz** [comment]
It's not. We are not planning to implement it any time soon. I should have clarified it before closing it.
