### ISSUE TITLE
Allow overriding of the service name in traces

### ISSUE THREAD

**Issue by jmiettinen** [openfga/openfga#654]
Currently, name of the service in traces [is fixed to openfga](https://github.com/openfga/openfga/blob/6e4e76c/pkg/telemetry/tracing.go#L20).

This way, we could give the service a more clear name like "foo-authorization" that matches the domain better.

_It seems that not much is needed for this and I have something sketched out in https://github.com/openfga/openfga/pull/652 but I am not sure if we'd want to test this (no other similar functionality is tested)._

**Comment by jon-whit** [comment]
#652 will be included in our next release.

**Comment by miparnisari** [comment]
Released in [v0.4.3](https://github.com/openfga/openfga/releases/tag/v0.4.3).
