### ISSUE TITLE
I have a suggestion for PostgreSQL that will improve its performance.

### ISSUE THREAD

**Issue by xXAvoraXx** [openfga/openfga#670]
While searching for databases suitable for our microservices structure, I came across Citus Data. They talk about ambitious performance improvements for Citus Data Postgresql. From what I've reviewed, Microsoft bought Citus Data and it's completely open source. While browsing OpenFGA's github repos sometimes, I see that postgres-related performance improvements are being made, so I wanted to post it here as a suggestion.

'Why Shard Postgres? Performance
See how Citus gives this application ~20X faster transactions and 300X – 150,000X faster analytics queries.'

Citus = Postgres At Any Scale
The Citus database gives you the superpower of distributed tables. Because Citus is an open source extension to Postgres, you can leverage the Postgres features, tooling, and ecosystem you love. And in Citus 11, you can now query from any node—plus we’ve open sourced the few remaining Citus Enterprise features. With Citus, you can scale from a single node to a distributed cluster, giving you all the greatness of Postgres—at any scale.

[Citus Data Link](https://www.citusdata.com/)

Github repo
https://github.com/citusdata/citus

**Comment by jon-whit** [comment]
@xXAvoraXx thanks for the suggestion! In the coming months we're going to be looking into the implications of running OpenFGA with a Postgres HA topology. There are a lot of Postgres HA options on the market including self-managed solutions and solutions managed by a database provider:

( Managed )
Cloud SQL - https://cloud.google.com/sql/postgresql
AWS RDS - https://aws.amazon.com/rds/
AWS Aurora - https://aws.amazon.com/rds/aurora/

( Self Managed )
Citus -  https://www.citusdata.com/

It is also worth considering database solutions that are Postgres compatible but part of the NewSQL variant of SQL database technologies, which bring HA and multi-regional capabilities natively to the database implementation. Postgres wasn't natively designed to be run in multi-region HA topology with regional transactions, and so it may be worth considering NewSQL technologies including:

* CockroachDB - https://www.cockroachlabs.com/
* YugaByte - https://www.yugabyte.com/
