### ISSUE TITLE
Server emits 500 internal error for invalid store name on Streamed List Object

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#678]
POST 

`http://localhost:8080/stores/ZAP%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%0A/streamed-list-objects`

(note the encoded `\n` at the end of the store_id path parameter)

will return 500 internal error with body 

```json
{
    "code": "internal_error",
    "message": "invalid header field value for \"openfga-store-id\""
}
```

It looks like the [streamserver interceptor](https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/validator#StreamServerInterceptor) does not guarantee that the validation will happen before the mux tries to read the header.  It only guarantees that it will happen before reaching userspace handler.

---

NOTE: this error only happens in streamed list object API.  Non-streamed API returns 400 bad request:

```jon
{
    "code": "validation_error",
    "message": "invalid ListObjectsRequest.StoreId: value does not match regex pattern \"^[ABCDEFGHJKMNPQRSTVWXYZ0-9]{26}$\""
}
```

**Comment by miparnisari** [comment]
The curious/concerning bit is that the error returned to the customer is wrong

```json
{
    "code": "internal_error",
    "message": "invalid header field value for \"openfga-store-id\""
}
```

but the OpenFGA logs do show the right log 🤔 

```text
2023-06-09T13:44:52.832-0700    INFO    grpc_req_complete       
{
  "grpc_service": "openfga.v1.OpenFGAService",
  "grpc_method": "StreamedListObjects",
  "grpc_type": "server_stream",
  "request_id": "fc4c9596-0806-4949-b084-927682e19d7b",
  "raw_request": {
    "store_id": "01H2E26SMF66C2D0W4KDV5WKJR\n",
    "authorization_model_id": "",
    "type": "document",
    "relation": "owner",
    "user": "maria",
    "contextual_tuples": null
  },
  "store_id": "01H2E26SMF66C2D0W4KDV5WKJR\n",
  "peer.address": "127.0.0.1:59278",
  "grpc_code": 2000,
  "error": "rpc error: code = InvalidArgument desc = invalid StreamedListObjectsRequest.StoreId: value does not match regex pattern \"^[ABCDEFGHJKMNPQRSTVWXYZ0-9]{26}$\""
}

```

**Comment by miparnisari** [comment]
Also this error goes away if we remove/comment this line 

https://github.com/openfga/openfga/blob/7ab00c06953add36d811bc9d436f1b305fb5b447/pkg/middleware/storeid/storeid.go#L87

Which makes me thing that this line somehow produces an error and it makes its way to the error handler

https://github.com/openfga/openfga/blob/f15b5b7a42ca4ec039596b7995ce6bb646cd8043/cmd/run/run.go#L649-L652

**Comment by miparnisari** [comment]
https://github.com/grpc-ecosystem/go-grpc-middleware/issues/589

**Comment by miparnisari** [comment]
Potential work-around:

```go
storeID = removeNewlines(storeID)
grpc.SetHeader(r.ctx, metadata.Pairs("store-id-header", storeID))

func removeNewlines(s string) string {
	s = strings.ToUpper(s)
	if !strings.Contains(s, "\n") && !strings.Contains(s, "%0A") {
		return s
	}
	s = strings.ReplaceAll(s, "\n", "")
	s = strings.ReplaceAll(s, "%0A", "")
	return removeNewlines(s)
}
```

**Comment by poovamraj** [comment]
We are closing this for now as it is not high priority.
