### ISSUE TITLE
Best practice: call Check many times or ListObjects once?

### ISSUE THREAD

**Issue by xXAvoraXx** [openfga/openfga#686]
After the users login, the client sends a GetUserPermissions request to the backend api service, this request is sent to the openfga service as a listobjects query after it is processed on the backend. The listobject returns with the permission list associated with nearly 100 users. This list is important for the client, it opens the components that the user should see.

My question is, do you think the approach I wrote is correct? How do you hide or open the components that the user should see on the screen?

![image](https://user-images.githubusercontent.com/6988989/231567880-7f516901-fbf0-43d4-a0de-9647941dc875.png)

Instead of the listobjects solution, would it be better for each component to first go to the openFGA service and ask whether it will be displayed during rendering? But wouldn't this solution incur network costs?

![image](https://user-images.githubusercontent.com/6988989/231569162-7a95fd4b-94d8-41e8-a65c-eeed8b6fb783.png)

**Comment by rhamzeh** [comment]
Thanks for asking @xXAvoraXx 

Can you elaborate more?

You mention that:
> The listobject returns with the permission list associated with nearly 100 users
ListObjects generally returns the list of objects that a particular user has a certain relation to. Do you mean to say that you are getting the list of users that a user can access?

Something like the below?
```js
ListObjects({
  user: "user:anna",
  relation: " can_view",
  type: "user"
})
```

And that it is returning 100 objects of type user?

Or do you mean to say that you are running 100 ListObjects for 100 different users?

Can you also share how many components there are? Are they dynamic or do you know their IDs beforehand? Can you also share a bit the request you are making?

**Comment by xXAvoraXx** [comment]
For example, we have a react application on the front end. Here, I keep the components that the user can and cannot see on the screen with openfga. In order to do this, I make a request to the openfga listobjects api via the backend of our application after the user has logged in. This request time takes about 13-14 seconds, and this time gets longer every time a new user joins the system. I reduce these times with redis, but this is not the right approach.

As an idea, instead of getting all the privileges that the user has from the openfga api after login, can the client connect directly to the openfga api without a backend? There may be security issues this time around.

For example, while a component is rendering, it makes a request to the openfga api, can the user see this component or not? but if there are 50 components on the page, this means that 50 of them will request at the same time.

**Comment by rhamzeh** [comment]
For 50 objects, if you know the IDs of the objects beforehand, I would recommend using `BatchCheck`.

This is especially true for your case, where I know you have `and` and `but not` in your model, so ListObjects has suboptimal performance (you collaborate that when you say it takes 13+ seconds).

I would suggest testing it, but `BatchCheck` should take much less than that time.

**Comment by xXAvoraXx** [comment]
> For 50 objects, if you know the IDs of the objects beforehand, I would recommend using `BatchCheck`.
> 
> This is especially true for your case, where I know you have `and` and `but not` in your model, so `ListObjects` has sub-optimal performance (you corroborate that when you say it takes 13+ seconds).
> 
> I would suggest testing it, but `BatchCheck` should take much less than that time.

Is it possible to update information on how to use BatchCheck here?
https://openfga.dev/api/service

**Comment by rhamzeh** [comment]
`BatchCheck` is not an API method, it is just issuing parallel calls to the [`Check` API endpoint](https://openfga.dev/api/service#/Relationship%20Queries/Check).

The SDKs help you with that by handling parallelization and retries:
- [BatchCheck Docs in the JS SDK](https://github.com/openfga/js-sdk#batch-check)
- [BatchCheck Docs in the Go SDK](https://github.com/openfga/go-sdk#batch-check)
- [BatchCheck Docs in the .NET SDK](https://github.com/openfga/dotnet-sdk#batch-check)

It's not yet available in the Python SDK, but we're working on that.
