### ISSUE TITLE
Running Openfga in docker in Ubuntu causes error "context deadline exceeded"

### ISSUE THREAD

**Issue by velmohan** [openfga/openfga#700]
I am just tyring to experiment with openfga and ran the following commands in Ubuntu 18.04.6 LTS.

```
docker pull openfga/openfga
docker run -p 8080:8080 -p 3000:3000 openfga/openfga run
```

I get an error "context deadline exceeded" after the INFO message saying "grpc server listening on `0.0.0.0:8081'...
From the logs I can see the version being run is v0.3.7.

**Comment by velmohan** [comment]
I see the same error is mentioned in the following issue but they are not related I believe because by default TLS is disabled and I still get the error https://github.com/openfga/openfga/issues/640

**Comment by velmohan** [comment]
Thanks @rhamzeh . I just tried getting v1.0.1 specifically. I am still getting the same error.

**Comment by velmohan** [comment]
The issue was caused by my local proxy settings. Fixing that solved the issue.

**Comment by aaguiarz** [comment]
@velmohan That's great to hear. Can you expand more on how the proxy was configured and how you fixed it? 

We've seen other users reporting this error and it was quite hard for us to help them.

**Comment by g3offrey** [comment]
@aaguiarz I personally fixed this issue running the container with environment variables `NO_PROXY=0.0.0.0,::1`
This is related to GRPC dial imho.
