### ISSUE TITLE
feat: Reject tuple input with direct relationship if not allowed instead of writing

### ISSUE THREAD

**Issue by dblclik** [openfga/openfga#73]
Currently, a `WriteCommand` (ref: `server/commands/write.go`) with a tupleset that is not valid because of attempting to write a `DirectUserset` (ref: `openfga/v1/authzmodel.proto` in [openfga/api](https://github.com/openfga/api)) is not rejected as invalid.  This tupleset does not cause an invalid authorization check (which is great), but it does create two potential pain points with users:

1. Services that write tuples to an fga store that violate this condition will not receive an error and assume that they provided a semantically valid tuple (they are already syntactically validated with the provided regex patterns); and,
2. fga admins (global or store) may get complaints of authorization checks failing that a service believes should be valid and, upon investigating see the invalid direct relationship, assume there is a deeper or more complex issue than simply violation of the indirect only relationship

Looking through `server/commands/write.go`, we do not currently pull in the `AuthorizationModel` (like in `server/commands/read_authzmodel.go`; though we do have the `StoreId` and `AuthorizationModelId` in the `req` input for `Execute` and should be able to fetch it), but if we did we would have access to the `TypeDefinitions` and should be able to then check if the `TypeDefinition.relations` map contains a `DirectUserset` or not

![Screen Shot 2022-06-26 at 2 45 10 PM](https://user-images.githubusercontent.com/3995753/175831717-f7b3d839-1a44-4204-92be-66e82d433f5a.png)
.

**Comment by dblclik** [comment]
I am hoping to try and implement the resolution to this (even just to get more hands on if not accepted), but am not against this being picked up by someone more comfortable with the openfga code base.

**Comment by dblclik** [comment]
@adriantam - I think I've got my plan in order and will begin tomorrow, but wanted to put the idea down here to get any feedback or cautions.

As I see it, there are 4 scenarios in which direct assignment should be permitted
1. `this:{}`
2. When `this:{}` is on side of a `difference` (originally I thought this should be `base` only, but if it is in the `subtract` it still means that it could be directly assigned, only that would mean it will be interpreted by `check` and any other expansions as not actually the relation)
3. When `this:{}` is anywhere in an intersection
4. When `this:{}` is anywhere in a union

Thus, I plan to create a new function (would love suggestions on where to put it, whether that be in `write.go` or a `utils/...` or other) called `isDirectRelation` which takes in a `*openfgapb.Userset` and determines if it matches one of the above criteria.  If so, it will return `true`, if not it will return `false` (and a possibly `nil` error, ofc), which we can then use in `validateTuplesets` to determine if we should write the tuple or return error.

What are your thoughts on this, given the more concrete details?

**Comment by dblclik** [comment]
@adriantam @rhamzeh - hey all, apologies it has been a couple of weeks.  I finally had some time today and added in the changes to my branch in my [fork](https://github.com/dblclik/openfga/tree/feat/reject-direct-if-only-indir-allowed).  Everything except for unit tests has been completed (I've done extensive testing via the local playground and all appears to be in order).

When I ran `go test ./...` from root, I see this response for the `server/tests` set

**Comment by jon-whit** [comment]
@dblclik The server tests are in `server/server_test.go`. The `server/test` package defines shared tests (not test functions) that can be used for different storage implementations and they are publicly exported tests that can be used externally for services that embed OpenFGA as a server.

If you just want to run the server tests directly you can run the following command `go test -v ./server/...`. Or, to test OpenFGA for a specific storage engine, you can run commands such as:

```
go test -v ./server/... -run TestOpenFGAServer/TestPostgresDatastore
go test -v ./server/... -run TestOpenFGAServer/TestMemoryDatastore
```

**Comment by dblclik** [comment]
@jon-whit - perfect, thank you, that seems to work (and means my earlier run of `go test ./...` included it 🙌 ).  

I will work on adding tests for the new functionality, but can at least confirm that my additions have not broken anything prior :phew:

**Comment by dblclik** [comment]
@jon-whit @adriantam - hey all, I (finally) opened up [PR 114](https://github.com/openfga/openfga/pull/114).  I signed the CLA after opening it, so there's a mark in the PR history that it wasn't in place.  It should be good, but the license check workflow can't run until launched by an owner (like the other workflows).  Feel free to fire away with any/all comments and thoughts 🦖
