### ISSUE TITLE
change usages of karlseguin/ccache to use generics instead of type-assertions

### ISSUE THREAD

**Issue by jon-whit** [openfga/openfga#736]
We could change our usage of ccache in OpenFGA to use generics. We have a lot of type assertions on our ccache code, but that can change to generics. See the doc here:
https://github.com/karlseguin/ccache

For example:
```go
cachedEntry := cache.Get(cacheKey)

if cachedEntry != nil {
    return cachedEntry.Value().(*openfgapb.AuthorizationModel), nil
}
```
can become typed at compile time

```go
cache := ccache.New(ccache.Configure[*openfga.AuthorizationModel]())

cachedEntry := cache.Get(cacheKey)

if cachedEntry != nil {
    return cachedEntry.Value()
}
```

**Comment by harsha-aqfer** [comment]
@jon-whit Hi, I would like to work on this issue.

**Comment by harshabangi** [comment]
Hi @jon-whit, I would like to work on this issue?
