### ISSUE TITLE
Separate permissions for read and write requests

### ISSUE THREAD

**Issue by wilerson** [openfga/openfga#765]
Or _fine-grained authorization for your fine-grained authorization system_.

Right now, we can [configure authentication](https://openfga.dev/docs/getting-started/setup-openfga/docker#configuring-authentication), either via pre-shared keys or OIDC. The problem with that is that any authenticated user can do everything in OpenFGA, from checking permissions to rewriting the authorization model and deleting tuples.

We could have either a per-endpoint permission, or even just split between reads and writes as a first iteration. And then these permissions could be attributed to pre-shared keys or to OIDC audiences.

Is there anything like this in OpenFGA plans?

**Comment by rhamzeh** [comment]
Hi @wilerson 

It's on our roadmap: https://github.com/orgs/openfga/projects/1/views/1?pane=issue&itemId=25399898

You can also checkout an RFC contributed by the community and some of the discussions around it: https://github.com/openfga/rfcs/pull/10
