### ISSUE TITLE
Resolution string getting empty

### ISSUE THREAD

**Issue by rajujnvgupta** [openfga/openfga#767]
While hitting check api from go-sdk always getting empty resolution string e.g resolution="".

`{
    "allowed": true,
    "resolution": ""
}`

**Comment by rhamzeh** [comment]
Hi @rajujnvgupta 

This field is not meant for usage and will always return an empty string.

The [API docs](https://openfga.dev/api/service#/Relationship%20Queries/Check) call it out as for internal use only.



![Imagepipe_28.jpg](https://github.com/openfga/openfga/assets/536147/c7bb5c8f-b6ea-4aed-bed2-5ed9a1ee5e0f)
