### ISSUE TITLE
Simplify main/cmd/run/run.go

### ISSUE THREAD

**Issue by aaguiarz** [openfga/openfga#773]
A simple way to enable customers extend OpenFGA is to let them instantiate the OpenFGA server as a library, and configure it with the middlewares/adapters they need.

To make that simpler, we need to remove as much code as possible from run.go and make it so it's only about configuring it. The rest of the logic should be reusable by anyone looking to use openfga as a library.

For example, the code executed conditionally "if config.HTTP.Enabled", "if config.Metrics.Enabled", "if config.Profiler.Enabled", "if config.GRPC.TLS.Enabled", should be in a different function.

**Comment by jon-whit** [comment]
> To make that simpler, we need to remove as much code as possible from run.go and make it so it's only about configuring it. The rest of the logic should be reusable by anyone looking to use openfga as a library.

Regarding the entrypoint of the standalone OpenFGA runtime (e.g. `cmd/run/run.go`), I'm not sure I agree that needs to change. However, I do agree that we can move some componentry that we depend on in the run entrypoint (middlewares etc..)  to the public `pkg` package, and this would allow for re-use elsewhere.

Using these shared components, developers can then use OpenFGA as an embedded library and expose the functionality a their own standalone server (e.g. create their own `cmd/run/run.go` file) with the embedded server and their own HTTP or gRPC service definitions that delegate to the RPC definitions of OpenFGA server core.
