### ISSUE TITLE
issue with expand api

### ISSUE THREAD

**Issue by rajujnvgupta** [openfga/openfga#778]
Model:

```py
model
  schema 1.1
type user
type doc
  relations
    define parent: [folder]
    define viewer: editor or viewer from parent or editor from parent 
    define editor: editor from parent
    
type folder
  relations
    define parent: [folder]
    define viewer: [user] or editor or viewer from parent or editor from parent
    define editor: [user] or editor from parent
    define can_view: viewer but not closed
    define can_edit: editor but not closed 
    define closed: [user, user:*] or closed from parent 
```
  
Tuples added: 
- {folder:note1, parent, folder:note2}
- {folder:note2, parent, folder:note3}
- {folder:note3, parent, folder:note4}
- {folder:note4, parent, folder:note5}
- {user:raju,  editor, folder:note1}
 
  
Check Resquest: 
Case 1:           
- check request for `{user:raju, can_view, folder:note5}` gives `true`, without adding tuple `{user:raju, closed, folder:note3}`        

Case 2: 
- check request for `{user:raju, can_view, folder:note5}` gives `false`, after adding tuple `{user:raju, closed, folder:note3}`
                           
           
case 1 and case2 working as expected.
           
           
Expand API Request: 
    
```sh
curl --location --request POST '0.0.0.0:8080/stores/01GXSZX6XK4R9X6GQ416V2NGME/expand' \
    --header 'Content-Type: application/json' \
    --data-raw '{
      "tuple_key": {
        "object": "folder:note5",
        "relation": "can_view"
      },
      "authorization_model_id": "01H13NCSF3KFHW01392KT8DE4C"
    }
```
    
            
**Issue with expand api**
Without adding tuple  `{user:raju, closed, folder:note3}` gives exactly same  response as after adding this tuple. why?? 
               
Response:

```json        
       {
        "tree": {
            "root": {
                "name": "folder:note5#can_view",
                "difference": {
                    "base": {
                        "name": "folder:note5#can_view",
                        "leaf": {
                            "computed": {
                                "userset": "folder:note5#viewer"
                            }
                        }
                    },
                    "subtract": {
                        "name": "folder:note5#can_view",
                        "leaf": {
                            "computed": {
                                "userset": "folder:note5#closed"
                            }
                        }
                    }
                }
            }
        }
    }
```
        
        
  Please review @team openfga

**Comment by rhamzeh** [comment]
Hi @rajujnvgupta, what are you expecting the result to return?

Expand here is showing that the users who `can_view` `folder:note5` are `folder:note5#viewer` - `folder:note5#closed`. That is true regardless of whether you add: `"{user:raju, closed, folder:note3}"` or not (different note, different relation).

To see the change resulting from that tuple, you need to expand:
```
  "tuple_key": {
    "object": "folder:note3",
    "relation": "closed"
  },
```
