### ISSUE TITLE
Fix error message

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#814]
https://github.com/openfga/openfga/blob/61864b6fa8d8acaf79162b462e6785fb2fce276e/pkg/typesystem/typesystem.go#L727

This is adding a new line to the error message:

```json
{
"code":"invalid_authorization_model",
"message":"undefined relation\nadmin does not appear as a relation in any of the directly related user types [type:\"org\"]"
}
```

**Comment by krishnaduttPanchagnula** [comment]
errors.Join creates a new line and concatonates both msgs
