### ISSUE TITLE
Observed increased latency with increase in unrelated objects

### ISSUE THREAD

**Issue by jerclark** [openfga/openfga#818]
This seems similar to https://github.com/openfga/openfga/issues/727, but not exactly the same so I've opened a new issue.

## Version
docker pull openfga/openfga:sha256-3a9e727be2917b74614cb2d0edecc3fa87d5f143238c58650fa080c439dcacd6.sig

## Running
Locally

## Store
In-Memory only

## Model
```py
model
   schema 1.1
type user
type docgroup
  relations
    define viewer: [user]
type doc
  relations
    define can_read: viewer or viewer from parent
    define group: [docgroup]
    define viewer: [user]
```

## Test Tuples
```json5
// Single User, who is a viewer in only 1 group
{user: "user:1", relation:"viewer", object:"docgroup:1"}

// Then, for increasing N >= 1, where N = number of docgroups:
{user: "docgroup:1", relation:"group", object: "doc:1"}
{user: "docgroup:2", relation:"group", object: "doc:2"}
...
{user: "docgroup:N", relation:"group", object: "doc:N"}
```
Notice in the tupleset above, each document is only a part of 1 group. 

## Test Check:
```json5
{user:"user:1", relation: "can_read", object:"doc:1"}

// (always true, regardless of N)
```

## Observation:
As N increases (i.e. the total number of groups increases), the performance of the check degrades, even though user:1 is only part of 1 group, and doc:1 is only part of one group:

I ran 500 trials of each test below, passing the test check above to stores with increasing "Group Counts" (each tests was run independently, not concurrently):

Group Count | Avg Response Time (ms) | throughput (requests/sec) 
| ----------- | ----------- |-----------
1 | 1  | 554.93896
10 | 1 | 515.46392
100 | 1 |  559.91041
1000 | 1 | 507.09939
10000 | 4 | 214.50021
100000 | 22 | 43.46314

In absolute terms, these numbers are fine; but I didn't expect the total number of groups (even for a large number of groups) to impact the performance of my sample check.

I would expect performance impact if the number of documents in `docgroup:1` grows or if the number of groups to which `user:1` belongs grows - but not in my tested scenario.

## Question:
Is there another way to model this such that the total number of groups wouldn't impact performance in scenarios when the `user -> object` cardinality is stable?

**Comment by jerclark** [comment]
Thanks for the follow up @rhamzeh! 

Yes, the mismatch between the model and my tuples is accidental above. I updated the original comment so they both read "group" :)

I will look into postgres...

**Comment by miparnisari** [comment]
@jerclark your report led me to look a bit into the in-memory storage implementation and I noticed that we have some old code that we need to update :) see the bottom of https://github.com/openfga/openfga/issues/771
