### ISSUE TITLE
Broken link on production checklist

### ISSUE THREAD

**Issue by stupied4ever** [openfga/openfga#836]
At https://github.com/openfga/openfga#setup-and-installation the link to the production checklist is broken.

**Comment by miparnisari** [comment]
@adriantam is this the right link? https://openfga.dev/docs/getting-started/running-in-production

**Comment by adriantam** [comment]
> @adriantam is this the right link? https://openfga.dev/docs/getting-started/running-in-production

Yes, this is correct.
