### ISSUE TITLE
Support query in /read endpoint for all users with a type definition and a specific object

### ISSUE THREAD

**Issue by jerclark** [openfga/openfga#861]
# Consider this authorization model
```
model
  schema 1.1
type user
type application
type folder
  relations
    define admin: [user, application]
    define viewer: [user, application]
```

# With the following tuples:
```
{
    user: "user:alice",
    relation: "admin",
    object: "folder:1"
},
{
    user: "user:bob",
    relation: "viewer",
    object: "folder:1"
},
{
    user: "application:1",
    relation: "admin",
    object: "folder:1"
}
```

# I'd like perform the following query to POST /read:
```
{
 "tuple_key": {
     "object": "folder:1",
     "user": "user:"
    }
}
```

# With the goal of receiving:
```
{
    user: "user:alice",
    relation: "admin",
    object: "folder:1"
},
{
    user: "user:bob",
    relation: "viewer",
    object: "folder:1"
}
```

It seems similar to this type of request:
![image](https://github.com/openfga/openfga/assets/985022/d1c8d036-fcb0-49d7-8b8a-021c5df32e50)

But we exchanging the specificity from the user to the object.

Certainly, we could just look for all relations for the specific object and then filter by user type in application code - but I figured I'd post this here to see if others might be interested in this feature.

**Comment by aaguiarz** [comment]
Hi @jerclark 

This is something we have in our roadmap but it's not scheduled yet https://github.com/openfga/roadmap/issues/33
