### ISSUE TITLE
Minor optimization in ListObjects

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#863]
i’m reading ListObjects code and i see this:

https://github.com/openfga/openfga/blob/d2360092635abe5ae7876b31faf5f2be2e141391/pkg/server/commands/list_objects.go#L190-L207

This is good, but shouldn’t we _also_ have the following before we do the Check call? 

```go
if atomic.LoadUint32(objectsFound) >= maxResults { 
     return
}
```

Right now, we’ll do the Check and, if we’ve already hit the maxResults, we’ll throw the result away :grimacing:

**Comment by jingchu000** [comment]
Haha, you have already told me how to modify it, haven't you? i work it
