### ISSUE TITLE
Jaeger container in docker-compose is using memory backend

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#868]
https://github.com/openfga/openfga/blob/5ac6f9b6be6b4d5efb55f3195e929df0557d2ab1/docker-compose.yaml#L74

Jaeger container is using `memory` backend, so if the container is stopped, the traces are lost. If we want this Docker-compose to be somehow production-ready, we should support at least one persistent backend: https://www.jaegertracing.io/docs/1.18/deployment/#storage-backends

**Comment by jingchu000** [comment]
I don't have any ideas. Can you give me some hints

**Comment by Azanul** [comment]
I'd like to resolve this issue.

**Comment by Azanul** [comment]
To introduce a different storage backend (ElasticSearch) to Jaeger, we need to add a new service `elasticsearch` and point to it from `jaeger` service.

If that's what we are looking for, I'll submit a PR right away.

**Comment by jon-whit** [comment]
@Azanul introducing a storage backend service (e.g. ElasticSearch) seems like overkill for the use case here. Using a disk backed jaeger backend seems sufficient.

https://www.jaegertracing.io/docs/1.18/deployment/#badger---local-storage
