### ISSUE TITLE
Remove debug log level from standard http client

### ISSUE THREAD

**Issue by VeskoPavlov** [openfga/openfga#877]
Even thought that I have set the log level to info(I believe it is by default) and log format to json, there are logs in DEBUG level and non-json format when setting up the OIDC authentication.

From quick look, it seems like a LeveledLogger could be passed to the Client or just set the Client.logger to nil.

Following is an example of how the logs looks like:

`{"level":"info","timestamp":1689760220.505616,"msg":"🧪 experimental features enabled: []","build.version":"v1.2.0","build.commit":"bc6a45ade4ae02d389b2588ae3bb4676fdcf77ec"}

{"level":"info","timestamp":1689760220.5057163,"msg":"using 'memory' storage engine","build.version":"v1.2.0","build.commit":"bc6a45ade4ae02d389b2588ae3bb4676fdcf77ec"}

{"level":"info","timestamp":1689760220.5057275,"msg":"using 'oidc' authentication","build.version":"v1.2.0","build.commit":"bc6a45ade4ae02d389b2588ae3bb4676fdcf77ec"}

2023/07/19 09:50:20 [DEBUG] GET https://domain.io/.well-known/openid-configuration
2023/07/19 09:50:20 [DEBUG] GET https://domain.io/.well-known/jwks.json

{"level":"warn","timestamp":1689760220.946375,"msg":"grpc TLS is disabled, serving connections using insecure plaintext","build.version":"v1.2.0","build.commit":"bc6a45ade4ae02d389b2588ae3bb4676fdcf77ec"}

{"level":"info","timestamp":1689760220.9464252,"msg":"📈 starting metrics server on '0.0.0.0:2112'","build.version":"v1.2.0","build.commit":"bc6a45ade4ae02d389b2588ae3bb4676fdcf77ec"}

{"level":"info","timestamp":1689760220.9464777,"msg":"🚀 starting openfga service...","build.version":"v1.2.0","build.commit":"bc6a45ade4ae02d389b2588ae3bb4676fdcf77ec","version":"v1.2.0","date":"2023-06-30T20:11:20Z","commit":"bc6a45ade4ae02d389b2588ae3bb4676fdcf77ec","go-version":"go1.20.5"}

{"level":"info","timestamp":1689760220.9468043,"msg":"grpc server listening on '0.0.0.0:8081'...","build.version":"v1.2.0","build.commit":"bc6a45ade4ae02d389b2588ae3bb4676fdcf77ec"}

{"level":"info","timestamp":1689760220.94795,"msg":"HTTP server listening on '0.0.0.0:8080'...","build.version":"v1.2.0","build.commit":"bc6a45ade4ae02d389b2588ae3bb4676fdcf77ec"}

{"level":"info","timestamp":1689761570.4214308,"msg":"attempting to shutdown gracefully","build.version":"v1.2.0","build.commit":"bc6a45ade4ae02d389b2588ae3bb4676fdcf77ec"}

{"level":"info","timestamp":1689761570.422351,"msg":"server exited. goodbye 👋","build.version":"v1.2.0","build.commit":"bc6a45ade4ae02d389b2588ae3bb4676fdcf77ec"}`

**Comment by KlausVii** [comment]
Think this would fixed by initialising the httpClient here https://github.com/openfga/openfga/blob/main/internal/authn/oidc/oidc.go#L50 like this 
```
	client := retryablehttp.NewClient()
	client.Logger = nil
	oidc := &RemoteOidcAuthenticator{
		IssuerURL:  issuerURL,
		Audience:   audience,
		httpClient: client.StandardClient(),
	}
```
