### ISSUE TITLE
Protobuf Serialization Stability and Best Practices

### ISSUE THREAD

**Issue by jon-whit** [openfga/openfga#894]
A lot of our tests are "Golden Tests" and some of our functional behavior depends on stable protobuf serialization and a consistent serialization output. It is a well-known issue in the protobuf community that protobuf messages do not have a canonical serialization and cannot guarantee stable serialization finger prints over time.

See:
https://github.com/golang/protobuf/issues/1121
https://gist.github.com/kchristidis/39c8b310fd9da43d515c4394c3cd9510
https://protobuf.dev/reference/go/faq/#hash

We should do our diligence to make sure we are doing a semantic comparison of differences on the structured messages instead of comparing the byte representation(s) of the serialized messages. For example,

```go
func TestGolden(t *testing.T) {
    gotMsg := LoadConfig(...)
    gotBuf, err := protojson.Marshal(gotMsg)
    if err != nil {
        ...
    }
    wantBuf, err := ioutil.ReadFile(...)
    if err != nil {
        ...
    }
    // BAD: Syntactic comparison performed on the serialized message.
    if diff := cmp.Diff(wantBuf, gotBuf); diff != "" {
        t.Errorf("LoadConfig() mismatch (-want +got):\n%s", diff)
    }
}
```

vs

```go
func TestGolden(t *testing.T) {
    gotMsg := LoadConfig(...)
    wantBuf, err := ioutil.ReadFile(...)
    if err != nil {
        ...
    }
    wantMsg := new(configpb.Config)
    if err := prototext.Unmarshal(wantBuf, wantMsg); err != nil {
        ...
    }
    // GOOD: Semantic comparison performed on the structured message.
    if diff := cmp.Diff(wantMsg, gotMsg, protocmp.Transform()); diff != "" {
        t.Errorf("LoadConfig() mismatch (-want +got):\n%s", diff)
    }
}
```

[This comment](https://github.com/golang/protobuf/issues/1121#issuecomment-627554847) gives more insight and recommendations.

We should go through our code and make sure that we are testing with protobuf best-practices in mind and that we're also not strongly depending on any functional behavior that depends on stable serialization that may be problematic if that were to change.

**Comment by ilaleksin** [comment]
Hey,

I would be happy to help fixing this issue!

**Comment by adriantam** [comment]
Close via https://github.com/openfga/openfga/pull/1052
