### ISSUE TITLE
Unable to build when using openfga as library due to buf build migration

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#899]
For those using openfga as a library, build will fail due to buf.build [migrate from remote generation alpha](https://buf.build/docs/migration-guides/migrate-remote-generation-alpha/).  

You may see messages like 

```
sandcastle/server/server.go:58:9: cannot use s.openfgaServer.Read(ctx, req) (value of type *"go.buf.build/openfga/go/openfga/api/openfga/v1".ReadResponse) as *"buf.build/gen/go/openfga/api/protocolbuffers/go/openfga/v1".ReadResponse value in return statement
```

**Comment by jon-whit** [comment]
Fixed with #898 and released the changes in [v1.3.0](https://github.com/openfga/openfga/releases/tag/v1.3.0).

See https://github.com/orgs/openfga/discussions/187 for any further discussion around the release that introduced the fix.
