### ISSUE TITLE
Log validation errors whenever possible

### ISSUE THREAD

**Issue by jpadilla** [openfga/openfga#935]
Currently, validation errors are not being logged. This _could_ be an issue with the current ordering of interceptors.

See https://github.com/openfga/openfga/pull/926#discussion_r1287884783

**Comment by miparnisari** [comment]
It's actually two issues...

- The order of the interceptors https://github.com/openfga/openfga/blob/77f4ab850e75ded847468d9d6c8585d15aaaee34/cmd/run/run.go#L614-L644

I think the right order is:

```go
grpc_ctxtags.UnaryServerInterceptor(), // needed for logging 
requestid.NewUnaryInterceptor(), // always generate a request id
storeid.NewUnaryInterceptor(), // if available, add store_id to ctxtags
logging.NewLoggingInterceptor(logger), // logging
grpc_validator.UnaryServerInterceptor(),
grpc_prometheus.UnaryServerInterceptor(),
otelgrpc.UnaryServerInterceptor(),
grpc_auth.UnaryServerInterceptor(authnmw.AuthFunc(authenticator))
```

- The logging interceptor is ignoring the `err` parameter 😅 https://github.com/openfga/openfga/blob/bb1ed2e42efabf63da2fa37e12a05fb72e349c23/pkg/middleware/logging/logging.go#L75-L83
