### ISSUE TITLE
Unable to connect to an Azure-hosted Postgres instance

### ISSUE THREAD

**Issue by thisisxvr** [openfga/openfga#94]
I'm experimenting with connecting OpenFGA to an Azure managed Postgres instance by running the OpenFGA docker container locally, and passing the `postgres://` connection URI as the `OPENFGA_DATASTORE_CONNECTION_URI` env var. I've verified that I can connect to the Postgres instance through other means, but when I make a cURL request to create a new store in OpenFGA I get the following error:

```bash
ERROR   grpc error      {"error": "rpc error: code = Unknown desc = rpc error: code = Code(4000) desc = Internal Server Error", "request_url": "/stores"}
github.com/openfga/openfga/pkg/logger.(*ZapLogger).ErrorWithContext
        /home/runner/work/openfga/openfga/pkg/logger/logger.go:80
github.com/openfga/openfga/server.New.func1
        /home/runner/work/openfga/openfga/server/server.go:134
github.com/grpc-ecosystem/grpc-gateway/v2/runtime.HTTPError
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.10.3/runtime/errors.go:81
go.buf.build/openfga/go/openfga/api/openfga/v1.RegisterOpenFGAServiceHandlerClient.func12
        /home/runner/go/pkg/mod/go.buf.build/openfga/go/openfga/api@v1.1.16/openfga/v1/openfga_service.pb.gw.go:1639
github.com/grpc-ecosystem/grpc-gateway/v2/runtime.(*ServeMux).ServeHTTP
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.10.3/runtime/mux.go:386
github.com/rs/cors.(*Cors).Handler.func1
        /home/runner/go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231
net/http.HandlerFunc.ServeHTTP
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2084
net/http.serverHandler.ServeHTTP
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2916
net/http.(*conn).serve
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:1966
```

**Steps to reproduce:**
1. Populate `.openfga.env` with:
```
OPENFGA_DATASTORE_ENGINE=postgres
OPENFGA_DATASTORE_CONNECTION_URI=postgres://<username>:<password>@<server_name>.postgres.database.azure.com/<database_name>
OPENFGA_GRPC_TLS_ENABLED=false
OPENFGA_HTTP_TLS_ENABLED=false
```
2. Run `docker run --env-file ./openfga.env -p 8080:8080 openfga/openfga run`
3. Run ```curl -X POST 'localhost:8080/stores' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "openfga-demo"
}'``` in a separate terminal

**Comment by craigpastro** [comment]
Hi @thisisxvr! I think the problem here is that your Postgres instance does not have the required tables created yet. The ability to create the tables using the cli is in an upcoming PR (https://github.com/openfga/openfga/pull/56).

For the moment, the schema can be found https://github.com/openfga/openfga/blob/main/storage/postgres/migrations/20220617_initialize_schema.up.sql, so if you can execute this file on your instance, everything should work okay.

Please let me know if you have anymore questions!

**Comment by thisisxvr** [comment]
@craigpastro You are correct; I ran the schema and it worked. Thanks for the quick response!
