### ISSUE TITLE
ListObjects terrible performance with `but not` exclusion

### ISSUE THREAD

**Issue by KlausVii** [openfga/openfga#942]
Version: 1.3

We recently tried to add a blocklist to our model but it caused ListObject queries to go from ~30ms to over 1500-3000ms depending on the user. We have ~300 tuples in the store atm, with most of them being various projects.

Auth model:
```
model
  schema 1.1
type project
  relations
    ...
    define can_view: viewer but not revoked
    define owner_tenant: [tenant]
    define revoked: [user] or revoked from owner_tenant
    define viewer: [user] or editor
type tenant
  relations
    ...
    define revoked: [user]
type user
 ...
```

The perfomance hit is caused by adding the ` but not revoked` to `can_view`

Is `but not` just inherently bad for performance? Or are we doing something silly with our model?

**Comment by jon-whit** [comment]
@KlausVii how many objects is the ListObjects call  for the `project#can_view` relation expected to return? If the number is high, then the higher latency is not too out of the ordinary. If an intersection `a and b` or an exclusion `a but not b` is involved in the relationship, we end up resolving the lookup with concurrent Checks. The more objects there are expected to be returned, then worse the latency can become.

For us to better assist you, could you share what your server settings are set to, what database are you using, what version of OpenFGA, etc..?

**Comment by KlausVii** [comment]
@jon-whit Thanks for the reply!

We expect on the order of 10-50 projects to be returned in most cases, from 1000s of projects in the tuples once we are fully up and running. Most users would probably not be revoked from anything usually.

I think the caching work will help substantially, since the main use case is that a user is revoked from a tenant and is therefore not allowed to access any of that tenant's projects. 

Does the fact `[user]` is included under `revoked` in the project mean that fga would still need to check `project:1#revoked@user:jon` for every project anyway? 

Is the current algo doing a separate revoked SQL query for each project in the list?

Another possible speed could be to internally list all projects a user `can_view` and then subtract all the `revoked` ones; these 2 queries are very fast individually without the `but not` in the model. Not sure how you would figure that out programatically though.

We are running:
- version 1.3 
- default options
- postgres db 
- inside an EKS cluster.

**Comment by jon-whit** [comment]
@KlausVii is this still an issue since the `v1.2.0` release and with the query cache enabled? The optimizations included in `v1.2.0` should have helped by a noticeable amount.

**Comment by jon-whit** [comment]
@KlausVii did the check query cache that we released in `v1.3.1` help? If so, can we close? If not, I'd like to understand the behavior better so we can best assist. Are you still seeing the issue with `v1.3.1` and the check query cache enabled?

**Comment by miparnisari** [comment]
@KlausVii i'm going to close this issue, since it has become stale. If you are still experiencing problems, please open a new one. Thank you!

**Comment by KlausVii** [comment]
@miparnisari @jon-whit  I just got around to retesting, putting the `but not`s back into our model and the results were not encouraging. Our basic checks went from requiring 1-3 db queries to 10+ and avg latency of ~10ms to ~80ms. We are on the latest version 1.4.2.

Our list objects calls also suffered, though we are moving away from using that endpoint since it is not very useful for any marginally large lists.

Could we reopen this issue?

**Comment by miparnisari** [comment]
@KlausVii can you open a new issue for the Check API with more details so we can reproduce?
