### ISSUE TITLE
Support Contextual Tuples in Expand

### ISSUE THREAD

**Issue by geoffroybraun** [openfga/openfga#951]
Hi,

recently, I had a development that required a lot of http calls, and I wondered if we could discuss that together using an example to reduce those calls amount.

Let's take the following authorization model, where users are owners of houses and a house belongs to a quarter.

```yaml
model
    schema 1.1
type user
type house
    relations
        define owner: [user]
type quarter
    relations
        define belong_to: [house]
```

The use case I had to implement whould be : retrieve all houses user X owns in quarter Y.

Actually, to reach that goal, I would have to:
* get all houses which belong to quarter Y.
* for each house, check that user X owns it.

The improvement I have in mind is something similar to the `contextual_tuples` concept we can use in the `Check` endpoint, but to contextualize the request when reading, expanding or listing.

The request would look like this:

```json
{
    "tuple_key": {
        "user": "user:X",
        "relation": "owner",
        "object": "house:"
    },
    "contextual_tuple_keys": [
        {
            "user": "house:",
            "relation": "belong_to",
            "object": "quarter:Y"
        }
    ]
}
```

As you can see in the example above, the `house` type is used both as an object in the `tuple_key` property AND as a user in the `contextual_tuple_keys` one. This means that I would like to get all houses the user X owns as far as every returned house belongs to quarter Y. The `contextual_tuple_keys` would be an array, meaning we could provide many keys to contextualize the result using an `AND` statement when querying data.

As usual, please let me know if this makes sense for you or if you need further informations. Cheers!

**Comment by aaguiarz** [comment]
Hi @geoffroybraun 

ListObjects currently supports contextual tuples, and Expand should but it's not yet. 

A way you could address the scenario you mentioned above would be with a model like:

```
model
  schema 1.1
type user

type house 
  relations
    define owner: [user]
    define quarter: [quarter] 
    define owner_in_quarter: owner and user_in_context from quarter

type quarter
  relations 
    define user_in_context: [user]
 ```
 
You can call ListObjects for a specific user, the 'house' type, and a contextual tuple like:

```
user: "user:anne"
relation: "user_in_context"
object: "quarter:quarter-id"
```

Would that work?

**Comment by geoffroybraun** [comment]
Hi @aaguiarz,

I can't believe I miss the part in the authorization model where users can be retrieved directly from the quarter... I'm really sorry, here's the updated authorization model for my example:

```yaml
model
    schema 1.1
type user
type house
    relations
        define owner: [user]
        define resident: [user] or owner
type quarter
    relations
        define belong_to: [house]
        define resident: resident from belong_to
```

With that, we can retrieve:
* users in a specific house using the `resident` relation on the `house` type
* users in a specific quarter using the `resident` relation on the `quarter` type, which uses object-to-object relations through the `belong_to` relation.

Based on my use case _retrieve all houses user X owns in quarter Y_, I tried your solution on the `list-object` endpoint using the following JSON content:

```json
{
    "authorization_model_id": "{{AuthorizationModelId}}",
    "type": "house",
    "relation": "owner",
    "user": "user:X",
    "contextual_tuples": {
        "tuple_keys": [
            {
                "object": "quarter:Y",
                "relation": "resident",
                "user": "user:X"
            }
        ]
    }
}
```

Unfortuantely, I received an error message stating `Invalid tuple 'object:"quarter:Y" relation:"resident" user:"user:X"'. Reason: type 'user' is not an allowed type restriction for 'quarter#user'`. I believe this is exactly why you suggested another approach with your authorization model, but it is something we don't want to do, for users can **not** directly be added to a quarter from a business point of view; users can only be retrieved from a quarter, not inserted, and your authorization model could allow an application to do so.

Please let me know if this makes sense for you. Thanks!

**Comment by miparnisari** [comment]
This task should be relatively easy:

1. Add validation similar to the one we have in Check and ListObjects: 
- https://github.com/openfga/openfga/blob/164963facc61241e1378d8fefb6632c700407163/pkg/server/server.go#L591-L595
- https://github.com/openfga/openfga/blob/164963facc61241e1378d8fefb6632c700407163/pkg/server/commands/list_objects.go#L170-L174
2. Inside `Expand.Execute` https://github.com/openfga/openfga/blob/164963facc61241e1378d8fefb6632c700407163/pkg/server/commands/expand.go#L45 create a wrapper over the datastore using https://github.com/openfga/openfga/blob/164963facc61241e1378d8fefb6632c700407163/pkg/storage/storagewrappers/combinedtuplereader.go#L14-L16
3. Add a unit test that mocks `datastore.Read`

**Comment by sujitha-av** [comment]
Hi! I’m interested in working on this issue. Could you please assign it to me?

**Comment by aaguiarz** [comment]
Thanks @sujitha-av! Assigned!

**Comment by JanumalaAkhilendra** [comment]
If this issue is still open I would like to work on this, please assign it to me. 
Thank you

**Comment by sujitha-av** [comment]
Hey all, I am unable to actually write the tests for this and not sure if I am [proceeding](https://github.com/sujitha-av/openfga/blob/94bf8578672c20ec3789a2b50c8fbfe2a910564b/pkg/server/server.go#L1062C18-L1062C24) in the right way. I would like to pass it on someone else. @JanumalaAkhilendra please continue with this. Modifying the API [will be done](https://github.com/openfga/api/pull/202), please continue with the rest.
