### ISSUE TITLE
ListObjects should limit number of DB reads on every call

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#955]
As a follow-up of https://github.com/openfga/openfga/pull/860

We should have `ConnectedObjectsQuery.Execute()` call https://github.com/openfga/openfga/blob/eb44459b0732e85a93dba8d993a6220aff7647d7/pkg/storage/storagewrappers/boundedconcurrency.go#L38

with the parameter `maxConcurrentReadsForListObjects`, so that one ListObjects call doesn't hog all DB resources.

**Comment by MeenuyD** [comment]
Can you guide me on how I would like to work on this issue Can you how should i start?

**Comment by adriantam** [comment]
> Can you guide me on how I would like to work on this issue Can you how should i start?

Thank you for your interest in contributing to OpenFGA, @MeenuyD !

I'm going to complete the work in this particular task. I am currently working on a similar code path for `listObjects`, which should log the number of database reads in trace information (related to issue https://github.com/openfga/openfga/issues/956). As a result of working on the same codebase for my other PR, I have a good understanding of what needs to be done here. 

However, please don't hesitate to tackle any other issues listed in the [issues section](https://github.com/openfga/openfga/issues)! We would greatly appreciate your contributions elsewhere.

Thanks again!

**Comment by MeenuyD** [comment]
ok thank you
