### ISSUE TITLE
Docker manifest for arm/v7 missing

### ISSUE THREAD

**Issue by dv29** [openfga/openfga#983]
Hi, thank you for creating such an awesome project.
I'm currently working on a small project that I'm trying to deploy on Ordoid XU-4 (Raspberry PI alternative) that has `linux/arm/v7` architecture. I cant pull the docker image and run it locally. Is there a possibility to add the arch to docker?

Following is the error 
`no matching manifest for linux/arm/v7 in the manifest list entries`

I've tried adding the `--platform linux/arm64` but it runs into a problem when starting the server
`/openfga exec format error`

I'd be happy to create a PR if it could be adopted

**Comment by dv29** [comment]
I was able to get it work with `platform: linux/amd64`

**Comment by rhamzeh** [comment]
Thanks for the update @dv29! In case you encounter any more issues, we would love a contribution. Right now we are using https://goreleaser.com/ to build multi target images, so if we can easily add support for linux/arm/v7, we can consider it
