### ISSUE TITLE
Change `ResolutionDepth` value in Check API

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#994]
## Problem

In Check API, `ResolutionDepth` starts at  `resolveNodeLimit`:

https://github.com/openfga/openfga/blob/c45c5bc8a14155ed38465bab5297af2bf1afaec9/pkg/server/commands/check_command.go#L89

 and if it hits 0, we throw an error

https://github.com/openfga/openfga/blob/b7bcc8453cd5b9201f477e3d394f7df23059d182/internal/graph/check.go#L444-L446

This has 2 problems:
- it is not intuitive. `Depth` in a tree is usually 0 at the root and increases as you go downward, not the other way around.
- it forces you to set this field every time you write a test that needs a `ResolveCheckRequest` object.

We should change this so that `Depth` starts at zero and throws an error here if it hits `maxAllowedDepth`.

## Task

To accomplish this, we must do this (in no particular order):

1. Change `NewCheckRequestMetadata` to NOT accept a `maxDepth` parameter.
2. Change `CheckQuery` to NOT store a `resolveNodeLimit` field.
3. Change `LocalChecker` struct to have a new field `maxResolutionDepth` and an `option` func to set this field.
4. Call the `option` func when the server is built: https://github.com/openfga/openfga/blob/a2af40aefd43e50fa70fc2a5a601aac4503cdc7b/pkg/server/server.go#L610-L612
5. Inside `LocalChecker`, change the `if` of when the error is thrown to `if req.GetResolutionMetadata().Depth == maxResolutionDepth` 
6. Inside `LocalChecker`, every time we do `GetRequestMetadata().Depth--` we should do `GetRequestMetadata().Depth++`.

And obviously fix any tests that may break because of this

**Comment by jon-whit** [comment]
We should standardize on ResolutionMetadata as a first-class citizen of the RPC inspired request input signatures instead of `ctx`. This is because ReverseExpand and Check will eventually be targets for remote dispatch resolution.

**Comment by Atharva1723** [comment]
Can I work on this issue ?

**Comment by aaguiarz** [comment]
Thanks @Atharva1723, I just assigned it to you

**Comment by Atharva1723** [comment]
Will start working Today 👍

**Comment by JanumalaAkhilendra** [comment]
If this issue is still open I would like to work on this, please assign it to me. 
Thank you
